Disaster: Window Class Reference
Window Class Reference
#include <NGLScene.h>
Public Member Functions
Window ()
class ctor for the main scene
~Window ()
class destructor
void initializeGL ()
Initialising scene
void paintGL ()
paint function
void resizeGL (QResizeEvent *_event)
Resizing the window
void resizeGL (int _w, int _h)
Resizing the window
Public Attributes
std::vector< GeneralObj > objectsVector
A vector to store the objects
Timer * m_timer
pointer to Timer class
ngl::Mat4 m_globalRotation
rotation of the world
ngl::Mat4 m_rotationCurrent
overall rotation of the world
int Rotationtimer =0
timer for the rotation
Private Member Functions
void loadTexture ()
function to load Textures in from the texture shader
void setEnemyRotForest ()
resetting enemy positions after rotations
void setEnemyRotGarden ()
void checkEnemyPlayerCollisions ()
void bumpEnemy ()
void setEnemy ()
sets all enemy movement states-being displayed either active or chasing player
void checkHit ()
checks amount of enemy-player hits
void loadMatricesToShader ()
load to shader function
void keyPressEvent (QKeyEvent *_event)
key press event
void mouseMoveEvent (QMouseEvent *_event)
mouse moved
void mousePressEvent (QMouseEvent *_event)
mouse pressed
void mouseReleaseEvent (QMouseEvent *_event)
mouse release
void wheelEvent (QWheelEvent *_event)
mouse wheel release
void keyReleaseEvent (QKeyEvent *_event)
function called when key is released
void Pause ()
function to pause game
void Resume ()
function that resumes game
void Reset ()
function that resets when a new game is created
void drawScene (const std::string &_shader)
draw function
void timerEvent (QTimerEvent *event)
timer event
void moveSphere ()
function that moves the player based on key inputs
void BoundingBoxCollisions ()
This method checks if the position of the sphere is within the extents of the bounding boxes.
Also used for item pickup.
ngl::Mat4 PivotRotation (ngl::Vec3 _position, ngl::Mat4 _rotation, ngl::Vec3 _initialRotation, ngl::Vec3 _scale)
function that will rotate objects around the centre
bool sphereSphereCollision (ngl::Vec3 _pos1, GLfloat _radius1, ngl::Vec3 _pos2, GLfloat _radius2)
A method to test if two spheres are colliding.
Private Attributes
std::unique_ptr< EnemyState > m_enemy
pointer to EnemyState
ngl::Mat4 m_enemyGlobalRotation
rotation matrix for first enemy group
ngl::Mat4 m_enemyGlobalRotation2
rotation matrix for second enemy group
ngl::Vec3 newEnemyRotPos
new rotation matrix for Forest enemy group
ngl::Vec3 newEnemyRotPos2
new rotation matrix for Garden enemy group
int m_hit
enemy-player hit count
int m_spinXFace
variables for mouse move event
int m_spinYFace
variables for mouse move event
int m_origX
variable for mouse event
int m_origY
variable for mouse event
int m_origXPos
variable for mouse event
int m_origYPos
variable for mouse event
int m_width
width of window
int m_height
height of window
int m_lightTimer
light timer variable
int m_updateSphereTimer
timer for player movement
int m_redrawTimer
int cureStage = m_gamePlay.cureStage()
variable to control quest progress
int ingredients = m_gamePlay.ingredients()
variable to store how many ingredients have been picked up
int m_particleTimer
Partilce timer
int m_safeFromEruptionUiTimer
a timer that I increment to to control how long the game draws a message for the user
int m_gameTimerStarterCounter
timer that turns on the general gameplay timer e,g plague and volcano timers, else it doesn't work
int m_fpsTimer
bool m_isAttacking =false
enemy Forest attack state
bool m_isAttacking2 =false
enemy Garden attack state
bool m_rotate
boolean for mouse move event
bool m_translate
boolean for mouse move event
bool lavender = m_gamePlay.lavenderFlag()
flag to show you picked up lavender
bool roses = m_gamePlay.rosesFlag()
flag to show you picked up roses
bool mercury = m_gamePlay.mercuryFlag()
flag to show you picked up mercury
bool cloves = m_gamePlay.clovesFlag()
flag to show you picked up cloves
bool lightMovementAB =true
Booleans for the light movement of light1
bool lightMovementBC =false
Booleans for the light movement of light1
bool lightMovementCD =false
Booleans for the light movement of light1
bool lightMovementDA =false
Booleans for the light movement of light1
bool volcanoTime
Boolean for the volcano time
bool m_isSafeFromEruption
boolean to ask if the player is safe from eruption
bool m_isSafeFromEruptionTimerTriggered
boolean to ask if the safeFromEruptionTimer is triggered
std::unique_ptr< Sphere > m_sphere
pointer to the player's position and cube rotation class
std::unique_ptr< ngl::Light > m_light
unique pointer to light1
std::unique_ptr< ngl::Light > m_light2
unique pointer to light2
std::unique_ptr< ngl::Light > m_light3
unique pointer to light3
std::unique_ptr< ngl::Light > m_light4
unique pointer to light4
std::unique_ptr< SphereBump > m_sphereBump
A pointer to the sphere bump
std::unique_ptr< ngl::Obj > m_menuBackground
obj of our background
std::unique_ptr< Terrain > m_terrain
pointer to the terrain class
std::unique_ptr< ngl::Text > m_text1
instances for the on screen text printing
std::unique_ptr< ngl::Text > m_text2
std::unique_ptr< ngl::Text > m_printVtimer
std::unique_ptr< ngl::Text > m_printPtimer
std::unique_ptr< ngl::Text > m_printInstructions
std::unique_ptr< ngl::Text > m_printMenu
std::unique_ptr< Emitter > m_emitter
pointer to the emitter class
ngl::Vec3 cube [6][1599]
ngl::Vec3 m_lightPosition1
Position of light 1
ngl::Vec3 m_lightPosition2
Position of light 2
ngl::Vec3 m_lightPosition3
Position of light 3
ngl::Vec3 m_lightPosition4
Position of light 4
ngl::Vec3 m_modelPos
model position
ngl::Vec3 m_treePosition
getting the tree position to figure out if player is on that side
ngl::Vec3 m_lavenderPosition
getting the lavender position to figure out if player is on that side
ngl::Vec3 m_spread
Spread variable for the particles
ngl::Vec3 cubes [7][2]
stores the position of the first and the last small cube on one terrain (opposite corners)
ngl::Vec3 m_cubesFirstAndLast [7][2]
first and the last cube of one terrain (opposite corners)
ngl::Mat4 m_mouseGlobalTX
mouse transformation
ngl::Camera * m_cam
Pointer to our camera
ngl::Transformation m_transform
transformation
QSet< Qt::Key > m_keysPressed
for the key press event
Space * m_space
Pointer to our space background object
gamemenu m_menu
instance of class gamemenu.
UI m_UI
instance of clas UI.
gamePlay m_gamePlay
instance of gamePlay class
GLuint m_textureName
Texture name
GLfloat m_gravity
gravity varibale for the particle system
Detailed Description
Definition at line 38 of file NGLScene.h.
Constructor & Destructor Documentation
Window::Window ()
class ctor for the main scene
Class constructor
for the mouse event
set light positions
Definition at line 27 of file NGLScene.cpp.
References m_hit, m_isAttacking2, m_isSafeFromEruption, m_isSafeFromEruptionTimerTriggered, m_keysPressed, m_lightPosition1, m_lightPosition2, m_lightPosition3, m_lightPosition4, m_redrawTimer, m_rotate, m_safeFromEruptionUiTimer, m_spinXFace, m_spinYFace, and m_updateSphereTimer.
 {
     m_rotate=false;
     m_spinXFace=0;
     m_spinYFace=0;
     setTitle("Oh no! Disaster!");
     m_updateSphereTimer=startTimer(2);
     m_redrawTimer=startTimer(4);
     m_keysPressed.clear();
     m_lightPosition1.set(-3,3,-3);
     m_lightPosition2.set(0,3,0);
     m_lightPosition3.set(0,-3,3);
     m_lightPosition4.set(3,-3,-3);
     m_hit=0;
     m_isAttacking2=false;
     m_isSafeFromEruption = false;
     m_safeFromEruptionUiTimer = 51;
     m_isSafeFromEruptionTimerTriggered = false;
 }
Window::~Window ()
class destructor
Class destructor
Definition at line 54 of file NGLScene.cpp.
References m_timer.
 {
     delete m_timer;
     std::cout<<"Shutting down NGL, removing VAO's and Shaders\n";
 }
Member Function Documentation
void Window::BoundingBoxCollisions () private
This method checks if the position of the sphere is within the extents of the bounding boxes.
Also used for item pickup.
Access the extents of the bounding boxes
Determine whether the position of the sphere plus the radius is within the extents of the bounding boxes
objects interactions: depending on what the player is hitting and at what point of the game it is, the player can interact with certain objects (speak to doctor, pick up ingredients to cure the plague)
There is a collision
There is not a collision
turns off the timer for speaking to the plague doctor once its ran out of time, so icon undraws
Definition at line 1144 of file NGLScene.cpp.
References cloves, cureStage, UI::getUiTimer(), ingredients, lavender, m_gamePlay, m_sphere, m_UI, BBExtent::maxX, BBExtent::maxY, BBExtent::maxZ, mercury, BBExtent::minX, BBExtent::minY, BBExtent::minZ, objectsVector, roses, gamePlay::setGameWon(), UI::setTriggerTimer(), and UI::timerReset().
 {
     for(unsigned int i = 0; i < objectsVector.size(); ++i)
     {
         BBExtent objExtents = objectsVector[i].getExtents();
         if((m_sphere->getPosition().m_x + 0.2)>= objExtents.minX && (m_sphere->getPosition().m_x - 0.2)<= objExtents.maxX &&
            (m_sphere->getPosition().m_y + 0.2)>= objExtents.minY && (m_sphere->getPosition().m_y - 0.2)<= objExtents.maxY &&
            (m_sphere->getPosition().m_z + 0.2)>= objExtents.minZ && (m_sphere->getPosition().m_z - 0.2)<= objExtents.maxZ)
         {
             if (i==6)       //if colliding with the doctor
             {
                 //start timer for the dialogue to draw
                 m_UI.setTriggerTimer(true);
                 if (cureStage == 0)     //if quest not started yet
                 {
                     m_sphere->setHit();
                     cureStage=1;     //start quest
                 }
                 else if (cureStage == 2)    //player hasn't picked up all the ingredients for the plague cure
                 {
                     m_sphere->setHit();
                 }
                 else if (cureStage == 3)    //player has picked up all the ingredients
                 {
                     m_sphere->setHit();
                     m_gamePlay.setGameWon(true);
                 }
             }
             else if (i>=25 && i<=28)       //if colliding with one of the lavender plants
             {
                 if (cureStage>0 && lavender==false)
                 {
                     lavender=true;
                     objectsVector[i].pickup();
                     ingredients += 1;
                     if (ingredients == 4)   //if all the ingredients have been picked up
                     {
                         cureStage=3;
                     }
                     else
                     {
                         cureStage=2;
                     }
                 }
                 m_sphere->setHit();
             }
             else if (i==29 || i==30)       //if colliding with the roses
             {
                 if (cureStage>0 && roses==false)
                 {
                     roses=true;
                     objectsVector[i].pickup();
                     ingredients += 1;
                     if (ingredients == 4)   //if all the ingredients have been picked up
                     {
                         cureStage=3;
                     }
                     else
                     {
                         cureStage=2;
                     }
                 }
                 m_sphere->setHit();
             }
             else if (i==8)       //if colliding with the mercury
             {
                 if (cureStage>0 && mercury==false)
                 {
                     mercury=true;
                     objectsVector[i].pickup();
                     ingredients += 1;
                     if (ingredients == 4)   //if all the ingredients have been picked up
                     {
                          cureStage=3;
                     }
                     else
                     {
                         cureStage=2;
                     }
                 }
                 m_sphere->setHit();
             }
             else if (i==21)       //if colliding with the cloves
             {
                 if (cureStage>0 && cloves==false)
                 {
                     cloves=true;
                     objectsVector[i].pickup();
                     ingredients += 1;
                     if (ingredients == 4)   //if all the ingredients have been picked up
                     {
                          cureStage=3;
                     }
                     else
                     {
                         cureStage=2;
                     }
                 }
                 m_sphere->setHit();
             }
             else
             {
                 m_sphere->setHit();
             }
             break;
         }
         else
         {
             m_sphere->setNotHit();
             if(m_UI.getUiTimer() == 0 )
             {
                  m_UI.setTriggerTimer(false);
                  m_UI.timerReset();
             }
         }
     }
 }
void Window::bumpEnemy () private
Definition at line 1332 of file NGLScene.cpp.
References m_enemy, and m_sphereBump.
 {
       for (unsigned int i=0;i<5;i++)
     {
         //create enemy bump for each enemy at init positions
         m_sphereBump.reset(new SphereBump(m_enemy->enemyForest[i].getPosition()));
         m_sphereBump.reset(new SphereBump(m_enemy->enemyGarden[i].getPosition()));
      }
 }
void Window::checkEnemyPlayerCollisions () private
Definition at line 846 of file NGLScene.cpp.
References checkHit(), m_enemy, m_hit, m_sphere, and sphereSphereCollision().
 {
     for(unsigned int i=0;i<m_enemy->enemyForest.size();i++)
     {
     bool collide=sphereSphereCollision(m_sphere->getPosition(),0.1,m_enemy->enemyForest[i].getPosition(),0.1);
         if(collide)
         {
            m_enemy->enemyForest[i].setHit(collide,++m_hit);
            std::cout<<m_hit<<std::endl;
         }
     }
     for(unsigned int i=0;i<m_enemy->enemyGarden.size();i++)
     {
     bool collide=sphereSphereCollision(m_sphere->getPosition(),0.1,m_enemy->enemyGarden[i].getPosition(),0.1);
         if(collide)
         {
            m_enemy->enemyGarden[i].setHit(collide,++m_hit);
            std::cout<<m_hit<<std::endl;
         }
     }
    checkHit();
 }
void Window::checkHit () private
checks amount of enemy-player hits
Definition at line 875 of file NGLScene.cpp.
References m_gamePlay, m_hit, gamePlay::setGameLost(), and gamePlay::setHeartcount().
 {
     //converting how many times the enemies collide with the player into heartcount
     if(m_hit <= 0)
     {
         m_gamePlay.setHeartcount(5);
     }
     else if((0 < m_hit)  && (m_hit <= 6))
     {
         m_gamePlay.setHeartcount(4);
     }
     else if((6 < m_hit)  && (m_hit <= 12))
     {
         m_gamePlay.setHeartcount(3);
     }
     else if((12< m_hit)  && (m_hit <= 18))
     {
         m_gamePlay.setHeartcount(2);
     }
     else if((18 < m_hit)  && (m_hit <= 24))
     {
         m_gamePlay.setHeartcount(1);
     }
     else if (m_hit>=30)
     {
         //set heartcount and gamelost to represent the game being over
         m_gamePlay.setHeartcount(0);
         m_gamePlay.setGameLost(true);
     }
 }
void Window::drawScene (const std::string & _shader) private
draw function
draw function
if the timer for the UI is needed
if the timer goes over 130 frames, it will stop incrementing
triggering volcano eruption screen when you're safe
if the timer for a safe by volcano screen is triggered, start incrementing value
while the timer is less than 50 draw the icon to indicate that player is safe from eruption
getting the position of the tree to figure out if the player is on the right face
getting the position of the lavender to figure out if the player is on the right face
getting the matrix from sphere class to set the new rotation
stops rotation and enables player movement again
get an instance of the shader library
set phong as primary shader
pause the game
draw menu
pauses the timer for the volcano and plague spread
sets the variable to start the game timer to 0
set phong shader as primary shader
starts the timer, it doesn't get set back to 0 elsewhere so it is used only to start the main game timer when you press play game for the first time.
set shader to flat diffuse and assign colour
get width and height of plane edge here;
scaling of cube
set shader flag to 0 to enable phong calculations
Draw background
get an instance of VAE primitives
the position and the scale for the small cubes on each terrain
receiving the scales and positions of the small cubes in each terrain
storing the rotated terrain positions
temporary transformation variable storing the scales and positions of each small cube
looping through each side and each small cube to draw them
updating the positions of the small cubes
applying the transformations depending on the new positions
updating the first and the last small cube on each terrain
loading shader
drawing one small cube
If volcano is upside down and erupts you survie
if volcano is upside down yet doesnt erupt you surive
if volcano is positioned anywhere else and doesnt erupt you survive
if volcano is positioned anywhere else and erupts you lose
tells the game that the volcano has erupted
–————————————— draw meshes –—————————————//
Set use of texture shader
Set the position of the object to the position after the rotation of the cube has been taken into account
Draw the objects in the vector to the scene
draws the UI if set to true
opens the menu, inputs the heartcount and cure stage of the game
if the player has won the game
if the player loses
if statements that have multiple condiitons to prevent several loss screens drawn at the same time
draws death screen
pause game
sets the exit flag to true, allowing the player to choose whether or not to restart game
if volcano has erupted
death by volcano screen
pause
draw exit options, allow for user to exit/restart game
death by volcano screen
pause
draw exit options, allow for user to exit/restart game
instruction page
Definition at line 317 of file NGLScene.cpp.
References Timer::counterD, cureStage, UI::deathByDiseaseScreen(), UI::deathByEnemiesScreen(), UI::deathByVolcanoScreen(), UI::decrementUITimer(), Space::draw(), gamemenu::drawInstructions(), gamemenu::drawMenu(), UI::drawUI(), gamePlay::gameDisease(), gamePlay::gameErupted(), gamePlay::gameLost(), gamePlay::gameWon(), gamemenu::getGamePlayBool(), gamemenu::getInstructionBool(), gamemenu::getMenuBool(), Timer::getPlagueTimer(), UI::getTriggerTimer(), gamemenu::getUiOpen(), UI::getUiTimer(), gamePlay::heartcount(), Timer::isErrupting(), loadMatricesToShader(), m_cubesFirstAndLast, m_emitter, m_enemyGlobalRotation, m_enemyGlobalRotation2, m_gamePlay, m_gameTimerStarterCounter, m_globalRotation, m_gravity, m_isSafeFromEruption, m_isSafeFromEruptionTimerTriggered, m_lavenderPosition, m_menu, m_modelPos, m_mouseGlobalTX, m_rotationCurrent, m_safeFromEruptionUiTimer, m_space, m_sphere, m_spinXFace, m_spinYFace, m_spread, m_terrain, m_timer, m_transform, m_treePosition, m_UI, objectsVector, Pause(), PivotRotation(), Reset(), Resume(), Rotationtimer, s_sphereUpdate, UI::SafeFromVolcanoScreen(), Timer::setActive(), setEnemy(), UI::setExitQuestionFlag(), gamePlay::setGameDisease(), gamePlay::setGameErupted(), gamePlay::setGameLost(), UI::setTriggerTimer(), gamemenu::setUiOpen(), Timer::timerStart(), and UI::winScreen().
 {
     if(m_UI.getTriggerTimer() == true)
     {
         m_UI.decrementUITimer();
     }
     if(m_UI.getUiTimer() > 130)
     {
         m_UI.setTriggerTimer(false);
     }
     if(m_isSafeFromEruption == true)
     {
         //trigger timer
         m_isSafeFromEruptionTimerTriggered = true;
     }
     if(m_isSafeFromEruptionTimerTriggered == true)
     {
          m_safeFromEruptionUiTimer = m_safeFromEruptionUiTimer + 1;
          std::cout<<m_safeFromEruptionUiTimer<<std::endl;
     }
     if((m_safeFromEruptionUiTimer < 35) && (m_isSafeFromEruptionTimerTriggered == true) && m_menu.getUiOpen())
     {
         m_UI.SafeFromVolcanoScreen();
     }
     else if(m_safeFromEruptionUiTimer >= 35)
     {
         m_isSafeFromEruption = false;
         m_isSafeFromEruptionTimerTriggered = false;
         m_safeFromEruptionUiTimer = 0;
     }
     if(m_treePosition.m_y>5.3 && m_treePosition.m_y<5.5)
     {
         m_enemyGlobalRotation.identity();
     }
     if(m_lavenderPosition.m_y>5.4 && m_lavenderPosition.m_y<5.5)
     {
         m_enemyGlobalRotation2.identity();
     }
     if (m_sphere->rotateWorld==true)
     {
         m_globalRotation = m_sphere->getRotation();
         m_rotationCurrent=m_rotationCurrent*m_globalRotation;
         m_enemyGlobalRotation=m_enemyGlobalRotation*m_globalRotation;
         m_enemyGlobalRotation2=m_enemyGlobalRotation2*m_globalRotation;
         Rotationtimer++;
         s_sphereUpdate=0;
     }
     if (Rotationtimer==6)
     {
         Rotationtimer=0;
         m_sphere->rotateWorld=false;
         // updates first and last cubes in when rotating the world
         m_sphere->setFirstAndLastCubePositions(m_cubesFirstAndLast);
         // when rotating the world, the terrains have to be tracked to make the player move on top of them
         m_sphere->trackTerrain();
         s_sphereUpdate=0.04;
     }
     ngl::ShaderLib *shader=ngl::ShaderLib::instance();
     (*shader)["Phong"]->use();
     ngl::Mat4 rotX;
     ngl::Mat4 rotY;
     rotX.rotateX(m_spinXFace);
     rotY.rotateY(m_spinYFace);
     m_mouseGlobalTX=rotY*rotX;
     m_mouseGlobalTX.m_m[3][0] = m_modelPos.m_x;
     m_mouseGlobalTX.m_m[3][1] = m_modelPos.m_y;
     m_mouseGlobalTX.m_m[3][2] = m_modelPos.m_z;
     rotX.rotateX(m_spinXFace);
     rotY.rotateY(m_spinYFace);
     m_mouseGlobalTX=rotY*rotX;
     m_mouseGlobalTX.m_m[3][0] = m_modelPos.m_x;
     m_mouseGlobalTX.m_m[3][1] = m_modelPos.m_y;
     m_mouseGlobalTX.m_m[3][2] = m_modelPos.m_z;
     bool menu = m_menu.getMenuBool();
     if(menu == true )
     {
         Pause();
         m_menu.drawMenu();
         m_timer->setActive(false);
         m_gameTimerStarterCounter = 0;
     }
     bool m_gameOn = m_menu.getGamePlayBool();
     if (m_gameOn  == true)
     {
         (*shader)["Phong"]->use();
         if(!menu && m_gameTimerStarterCounter == 0)
         {
             m_timer->timerStart();
             m_gameTimerStarterCounter++;
             Reset();
         }
         Resume();
         m_transform.reset();
         {
             m_transform.setPosition(m_sphere->getPosition());
             loadMatricesToShader();
             shader->setUniform("Colour", 1.0f,0.0f,0.8f);//Set colour for flat diffuse colour shader
             shader->setUniform("myflag",1);//Flag enables the flat diffuse colour shader
             m_sphere->draw();
         }
         if(m_timer->getPlagueTimer()==true)setEnemy(); //if plague timer is active start doing enemy stuff
         float height=5;
         float width=5;
         m_sphere->planeEdge(width,height);
         m_transform.reset();
         {
             m_transform.setMatrix(PivotRotation(ngl::Vec3(0,0,0), m_rotationCurrent, ngl::Vec3(0,0,0), ngl::Vec3(width*2,width*2,width*2)));
             loadMatricesToShader();
             shader->setUniform("myflag",0);//Flag enables the phong shader
             ngl::VAOPrimitives::instance()->draw("cube");
         }
         m_space->draw();
         ngl::VAOPrimitives *prim=ngl::VAOPrimitives::instance();
         std::vector<ngl::Transformation> cubePosScale1;
         std::vector<ngl::Transformation> cubePosScale2;
         std::vector<ngl::Transformation> cubePosScale3;
         std::vector<ngl::Transformation> cubePosScale4;
         std::vector<ngl::Transformation> cubePosScale5;
         std::vector<ngl::Transformation> cubePosScale6;
         cubePosScale1=m_terrain->getCubePosScale1();
         cubePosScale2=m_terrain->getCubePosScale2();
         cubePosScale3=m_terrain->getCubePosScale3();
         cubePosScale4=m_terrain->getCubePosScale4();
         cubePosScale5=m_terrain->getCubePosScale5();
         cubePosScale6=m_terrain->getCubePosScale6();
         ngl::Mat4 newPosition;
         ngl::Transformation Tr1;
         for (int sideCounter=1; sideCounter<7; sideCounter++)
         {
             for (int loop=0; loop<1600; loop++)
             {
                 if (sideCounter==1) {Tr1=cubePosScale1.at(loop);}
                 else if (sideCounter==2) {Tr1=cubePosScale2.at(loop);}
                 else if (sideCounter==3) {Tr1=cubePosScale3.at(loop);}
                 else if (sideCounter==4) {Tr1=cubePosScale4.at(loop);}
                 else if (sideCounter==5) {Tr1=cubePosScale5.at(loop);}
                 else if (sideCounter==6) {Tr1=cubePosScale6.at(loop);}
                 newPosition = PivotRotation(ngl::Vec3(Tr1.getPosition()),m_rotationCurrent, ngl::Vec3(0,0,0),ngl::Vec3(Tr1.getScale()));
                 m_transform.setMatrix(newPosition);
                 if (loop==0) {m_cubesFirstAndLast[sideCounter][0]=ngl::Vec3(newPosition.m_30,newPosition.m_31,newPosition.m_32);}
                 if (loop==1599) {m_cubesFirstAndLast[sideCounter][1]=ngl::Vec3(newPosition.m_30,newPosition.m_31,newPosition.m_32);}
                 (*shader)["Phong"]->use();
                 loadMatricesToShader();
                 prim->draw("cube");
             }
         }
         m_transform.reset();
         {
             ngl::Mat4 new_transformations;
             new_transformations=PivotRotation(ngl::Vec3(0,5,0),m_rotationCurrent, ngl::Vec3(0,0,0),ngl::Vec3(1,1,1));
             m_emitter->setRot(m_rotationCurrent);
             m_emitter->setMouse(m_mouseGlobalTX);
             m_emitter->draw(m_timer->isErrupting());
             if(m_sphere->getVolcanoStatus()==true && m_timer->isErrupting()==true)
             {
                 m_gravity=-0.1;
                 m_spread.set(0.1,1,0.1);
                 m_isSafeFromEruption = true;
             }
             if(m_sphere->getVolcanoStatus()==true && m_timer->isErrupting()==false)
             {
                 m_gravity=-0.1;
                 m_spread.set(0.1,1,0.1);
             }
             if(m_sphere->getVolcanoStatus()==false && m_timer->isErrupting()==false)                m_sphere->setHit();
             {
                 m_gravity=-0.1;
                 m_spread.set(0.1,1,0.1);
             }
             if(m_sphere->getVolcanoStatus()==false && m_timer->isErrupting()==true)
             {
                 m_gravity=-9.8;
                 m_spread.set(1,1,1);
                 m_gamePlay.setGameErupted(true);
                 m_gamePlay.setGameLost(true);
             }
         }
         for (unsigned int i=0; i < objectsVector.size(); ++i)
         {
             (*shader)["Texture"]->use();
             m_transform.reset();
             ngl::Vec3 new_position;
             ngl::Mat4 transformation = PivotRotation(objectsVector[i].getPos(),m_rotationCurrent,objectsVector[i].getRot(),objectsVector[i].getScale());
             new_position = ngl::Vec3(transformation.m_30, transformation.m_31, transformation.m_32);
             objectsVector[i].setRotatedPos(new_position);
             m_transform.setMatrix(transformation);
             loadMatricesToShader();
             objectsVector[i].drawObj();
             if(i==12) {m_treePosition=new_position;}
             else if (i==22){m_lavenderPosition=new_position;}
         }
         if(m_menu.getUiOpen() == true)
         {
             m_UI.drawUI(m_gamePlay.heartcount(),cureStage);
         }
         if((m_timer->counterD > 120) && (m_gamePlay.gameLost() == false))
         {
             m_gamePlay.setGameDisease(true);
             m_gamePlay.setGameLost(true);
         }
         if((m_timer->counterD > 120) && (m_gamePlay.gameLost() == false))
         {
             m_gamePlay.setGameDisease(true);
             m_gamePlay.setGameLost(true);
         }
         if(m_gamePlay.gameWon() == true)
         {
             m_menu.setUiOpen(false);
             m_UI.winScreen();
             m_UI.setExitQuestionFlag(true);
             Pause();
         }
         if(m_gamePlay.gameLost() == true)
         {
             m_menu.setUiOpen(false);
             if((m_gamePlay.heartcount() == 0) && (m_gamePlay.gameErupted() == false))
             {
                 m_UI.deathByEnemiesScreen();
                 Pause();
                 m_UI.setExitQuestionFlag(true);
             }
            else if((m_gamePlay.gameErupted() == true) && (m_gamePlay.heartcount() > 0))
             {
                 m_UI.deathByVolcanoScreen();
                 Pause();
                 m_UI.setExitQuestionFlag(true);
             }
            else if((m_gamePlay.gameErupted() == false) && (m_gamePlay.heartcount() > 0) && (m_gamePlay.gameDisease() == true))
             {
                 m_UI.deathByDiseaseScreen();
                 Pause();
                 m_UI.setExitQuestionFlag(true);
             }
         }
    }
    bool _instructionMenu = m_menu.getInstructionBool();
    if(_instructionMenu == true )
    {
        m_menu.drawInstructions();
    }
 }
void Window::initializeGL ()
Initialising scene
initialising function
get an instance of the shader library
create the shader programs
attach the shaders to the shader program
Load the shader sources
compile the shaders
attach shader to main program
bind shader attributes
use the phong shader as the main shader
camera properties
set up the camera
reset light 1 with colour and mode and set transform
reset light 2 with colour and mode and set transform
reset light 3 with colour and mode and set transform
reset light 4 with colour and mode and set transform
Set material properties
set material diffuse
set material ambience
set material specular
set material specular component
load material properties to shader
initialise new timer
initialise emitter
set emitter to be dependant on camera
start particle timer
player, enemy, collision, cube and texture initiations
get an instance of VAO primitives
create player sphere
new enemy function,creates multiple enemies
initialise space background and load in texture
initialising all the objects to be printed on screen Objects on Village side of the world
Objects on Volcano side of the world
Objects on Starting side of the world
Objects on Dead side of the world
Objects on garden side of the world
creates the vao for a quad to be used for the menu and UI
start light timer
creating new terrain object
initializing terrain:
initialising the texts for on screen printing
Definition at line 80 of file NGLScene.cpp.
References bumpEnemy(), Colour, UI::initUI(), m_cam, m_emitter, m_enemy, m_light, m_light2, m_light3, m_light4, m_lightPosition1, m_lightPosition2, m_lightPosition3, m_lightPosition4, m_lightTimer, m_menu, m_particleTimer, m_printInstructions, m_printMenu, m_printPtimer, m_printVtimer, m_space, m_sphere, m_spread, m_terrain, m_text1, m_text2, m_timer, m_transform, m_UI, gamemenu::menuQuad(), and objectsVector.
 {
     ngl::NGLInit::instance();
     glEnable(GL_DEPTH_TEST);
     glEnable(GL_MULTISAMPLE);
     ngl::ShaderLib *shader=ngl::ShaderLib::instance();
     shader->createShaderProgram("Phong");
     shader->createShaderProgram("Texture");
     shader->createShaderProgram("UI");
     shader->attachShader("PhongVertex",ngl::ShaderType::VERTEX);
     shader->attachShader("PhongFragment",ngl::ShaderType::FRAGMENT);
     shader->attachShader("TextureVertex",ngl::ShaderType::VERTEX);
     shader->attachShader("TextureFragment",ngl::ShaderType::FRAGMENT);
     shader->attachShader("UiVertex",ngl::ShaderType::VERTEX);
     shader->attachShader("UiFragment",ngl::ShaderType::FRAGMENT);
     shader->loadShaderSource("PhongVertex","shaders/PhongVertex.glsl");
     shader->loadShaderSource("PhongFragment","shaders/PhongFragment.glsl");
     shader->loadShaderSource("TextureVertex","shaders/TextureVertex.glsl");
     shader->loadShaderSource("TextureFragment","shaders/TextureFragment.glsl");
     shader->loadShaderSource("UiVertex","shaders/uivertex.glsl");
     shader->loadShaderSource("UiFragment","shaders/uifragment.glsl");
     shader->compileShader("PhongVertex");
     shader->compileShader("PhongFragment");
     shader->compileShader("TextureVertex");
     shader->compileShader("TextureFragment");
     shader->compileShader("UiVertex");
     shader->compileShader("UiFragment");
     shader->attachShaderToProgram("Phong","PhongVertex");
     shader->attachShaderToProgram("Phong","PhongFragment");
     shader->attachShaderToProgram("Texture","TextureVertex");
     shader->attachShaderToProgram("Texture","TextureFragment");
     shader->attachShaderToProgram("UI","UiVertex");
     shader->attachShaderToProgram("UI","UiFragment");
     shader->bindAttribute("Phong",0,"inVert");
     shader->bindAttribute("Phong",1,"inUV");
     shader->bindAttribute("Phong",2,"inNormal");
     shader->bindAttribute("Texture",0,"inVert");
     shader->bindAttribute("Texture",1,"inUV");
     shader->bindAttribute("UI",0,"inVert");
     shader->bindAttribute("UI",1,"inUV");
     shader->linkProgramObject("Phong");
     shader->linkProgramObject("Texture");
     shader->linkProgramObject("UI");
     (*shader)["Phong"]->use();
     shader->setShaderParam1i("Normalize",1);
     ngl::Vec3 from(5,18,20);
     ngl::Vec3 to(0,0,0);
     ngl::Vec3 up(0,1,0);
     m_cam= new ngl::Camera(from,to,up);
     m_cam->setShape(45.0f,(float)720.0/576.0,0.05,350);
     ngl::Mat4 iv=m_cam->getViewMatrix();
     m_light.reset( new ngl::Light(m_lightPosition1,ngl::Colour(0.9,0.4,0.9,1.0),ngl::LightModes::POINTLIGHT));
     m_light->setTransform(iv);
     m_light2.reset( new ngl::Light(m_lightPosition2,ngl::Colour(0.8,1.5,0.8,1.0),ngl::LightModes::POINTLIGHT));
     m_light2->setTransform(iv);
     m_light3.reset( new ngl::Light(m_lightPosition3,ngl::Colour(0.8,1.0,1.0,1.0),ngl::LightModes::POINTLIGHT));
     m_light3->setTransform(iv);
     m_light4.reset( new ngl::Light(m_lightPosition4,ngl::Colour(1.0,0.0,1.0,1.0),ngl::LightModes::POINTLIGHT));
     m_light4->setTransform(iv);
     ngl::Material m;
     m.setDiffuse(ngl::Colour(0.6,1.0,0.6,1.0));
     m.setAmbient(ngl::Colour(1.0,1.0,1.0,1.0));
     m.setSpecular(ngl::Colour(1,1,1,1));
     m.setSpecularExponent(80);
     m.loadToShader("material");
     m_timer=new Timer();
     m_emitter.reset(new Emitter(ngl::Vec3(-1,10,-1),100,&m_spread));
     m_emitter->setCam(&*m_cam);
     m_particleTimer=startTimer(50);
     ngl::VAOPrimitives *prim=ngl::VAOPrimitives::instance();
     prim->createSphere("sphere",0.2,50);
     m_sphere.reset(new Sphere(ngl::Vec3(0,5.5,0)));
     m_transform.setPosition(m_sphere->getPosition());
     m_enemy.reset(new EnemyState);
     m_enemy->createEnemy();
     bumpEnemy();
     m_space = new Space("textures/Galaxy.tif",m_cam);
     objectsVector.push_back(GeneralObj(ngl::Vec3 (5.0, 3.0, 3.4), ngl::Vec3 (0, 90, -90), ngl::Vec3 (0.6, 0.6, 0.6), "Tower", "assets/Tower.obj", "textures/village.jpg"));               //0
     objectsVector.push_back(GeneralObj(ngl::Vec3 (5.0, 0.0, 3.5), ngl::Vec3 (0, 100, -90), ngl::Vec3 (0.6, 0.6, 0.6), "Village", "assets/House.obj", "textures/house.jpg"));              //1
     objectsVector.push_back(GeneralObj(ngl::Vec3 (5.0, -3.0, 2.3), ngl::Vec3 (0, 170, -90), ngl::Vec3 (0.5, 0.6, 0.6), "Village", "assets/House.obj", "textures/house.jpg"));             //2
     objectsVector.push_back(GeneralObj(ngl::Vec3 (5.0, -1.8, -0.5), ngl::Vec3 (0, 240, -90), ngl::Vec3 (0.5, 0.5, 0.5), "Village", "assets/House.obj", "textures/house.jpg"));            //3
     objectsVector.push_back(GeneralObj(ngl::Vec3 (5.0, -3.2, 0.1), ngl::Vec3 (0, 170, -90), ngl::Vec3 (0.6, 0.6, 0.6), "Village Tree", "assets/Tree_1.obj", "textures/tree1.jpg"));       //4
     objectsVector.push_back(GeneralObj(ngl::Vec3 (5.0, 4.0, -2.0), ngl::Vec3 (0, 100, -90), ngl::Vec3 (0.6, 0.5, 0.6), "Village Tree", "assets/Tree_1.obj", "textures/tree1.jpg"));       //5
     objectsVector.push_back(GeneralObj(ngl::Vec3 (5.2, 3.0, 1.3), ngl::Vec3 (0, 0, -90), ngl::Vec3 (0.25, 0.25, 0.25), "Doctor", "assets/Doctor.obj", "textures/doctor.jpg"));            //6
     objectsVector.push_back(GeneralObj(ngl::Vec3 (5.0, 3.4,-3.4), ngl::Vec3 (0,-30, -90), ngl::Vec3 (0.5, 0.5, 0.5), "DocHouse", "assets/House.obj", "textures/house.jpg"));              //7
     objectsVector.push_back(GeneralObj(ngl::Vec3 (5.2, 1.4, -3.0), ngl::Vec3 (0, 170, -90), ngl::Vec3 (0.2, 0.2, 0.2), "Mercury", "assets/Mercury.obj", "textures/darkgrey.jpg"));        //8
     objectsVector.push_back(GeneralObj(ngl::Vec3 (-5.4,-0.9,-0.7), ngl::Vec3 (0, 0, 90), ngl::Vec3 (4.6, 5.5, 4.6), "Volcano", "assets/Volcano.obj", "textures/volcano.jpg"));            //9
     objectsVector.push_back(GeneralObj(ngl::Vec3 (-6.4, -4.0, 0), ngl::Vec3 (0, 0, 100), ngl::Vec3 (0.5, 0.5, 0.5), "Flowers", "assets/Flowers.obj", "textures/flowers.jpg"));            //10
     objectsVector.push_back(GeneralObj(ngl::Vec3 (2.1, 6.0, -3.1), ngl::Vec3 (0,0,0), ngl::Vec3 (0.5, 0.5, 0.5), "RockClump", "assets/Rock_Clump.obj", "textures/grey.jpg"));             //11
     objectsVector.push_back(GeneralObj(ngl::Vec3 (0.0, 5.4, -4.0), ngl::Vec3 (0,0,0), ngl::Vec3 (0.5, 0.4, 0.5), "Forest", "assets/Tree_3.obj", "textures/tree3.jpg"));                   //12
     objectsVector.push_back(GeneralObj(ngl::Vec3 (2.6, 5.96, -2.0), ngl::Vec3 (0,30,0), ngl::Vec3 (0.5, 0.5, 0.5), "Forest", "assets/Tree_3.obj", "textures/tree3.jpg"));                 //13
     objectsVector.push_back(GeneralObj(ngl::Vec3 (4.0, 5.2, -3.9), ngl::Vec3 (0,0,0), ngl::Vec3 (0.5, 0.5, 0.5), "Forest addup", "assets/Tree_4.obj", "textures/tree4.jpg"));             //14
     objectsVector.push_back(GeneralObj(ngl::Vec3 (-2.5, 5.6, -2.0), ngl::Vec3 (0,0,0), ngl::Vec3 (0.5, 0.5, 0.5), "Forest addup", "assets/Tree_4.obj", "textures/tree4.jpg"));            //15
     objectsVector.push_back(GeneralObj(ngl::Vec3 (3.5, 1.5, -5.6), ngl::Vec3 (-90,0,0), ngl::Vec3 (0.5, 0.5, 0.5), "Rock Clump", "assets/Rock_Clump.obj", "textures/darkgrey.jpg"));      //16
     objectsVector.push_back(GeneralObj(ngl::Vec3 (0.2, 2.8, -5.7), ngl::Vec3 (-90,0,100), ngl::Vec3 (0.4, 0.4, 0.4), "Rock", "assets/Rock.obj", "textures/grey.jpg"));                    //17
     objectsVector.push_back(GeneralObj(ngl::Vec3 (-1.8, -4.4, -5.6), ngl::Vec3 (-90,0,100), ngl::Vec3 (0.5, 0.5, 0.5), "Rock Pile", "assets/Rock.obj", "textures/darkgrey.jpg"));         //18
     objectsVector.push_back(GeneralObj(ngl::Vec3 (-3.5, -3.3, -5.5), ngl::Vec3 (-90,0,45), ngl::Vec3 (0.6, 0.7, 0.8), "Rock Pile", "assets/Rock.obj", "textures/darkgrey.jpg"));          //19
     objectsVector.push_back(GeneralObj(ngl::Vec3 (-4.4, -4.3, -5.3), ngl::Vec3 (-90,0,100), ngl::Vec3 (1.0, 1.0, 1.0), "Rock Pile", "assets/Rock_Clump.obj", "textures/grey.jpg"));       //20
     objectsVector.push_back(GeneralObj(ngl::Vec3 (0.8, -2.8, -5.8), ngl::Vec3 (-90,0,100), ngl::Vec3 (0.4, 0.4, 0.4), "Cloves", "assets/Clove.obj", "textures/cloves.tif"));              //21
     objectsVector.push_back(GeneralObj(ngl::Vec3 (-2.3, -3.0, 5.5), ngl::Vec3 (90,0,100), ngl::Vec3 (0.6, 0.5, 0.6), "Tree", "assets/Tree_2.obj", "textures/tree2.jpg"));                 //22
     objectsVector.push_back(GeneralObj(ngl::Vec3 (-3.5, -2.0, 5.7), ngl::Vec3 (90,0,150), ngl::Vec3 (0.6, 0.6, 0.6), "Tree", "assets/Tree_2.obj", "textures/tree2.jpg"));                 //23
     objectsVector.push_back(GeneralObj(ngl::Vec3 (-1.2, -0.5, 6.0), ngl::Vec3 (90,0,180), ngl::Vec3 (0.6, 0.6, 0.6), "Tree", "assets/Tree_2.obj", "textures/tree2.jpg"));                 //24
     objectsVector.push_back(GeneralObj(ngl::Vec3 (-2.2, -2.2, 5.5), ngl::Vec3 (90,0,100), ngl::Vec3 (0.4, 0.4, 0.4), "Lavender", "assets/Lavender.obj", "textures/lavender.jpg"));        //25
     objectsVector.push_back(GeneralObj(ngl::Vec3 (-2.4, -1.0, 5.5), ngl::Vec3 (90,0,80), ngl::Vec3 (0.4, 0.4, 0.4), "Lavender", "assets/Lavender.obj", "textures/lavender.jpg"));         //26
     objectsVector.push_back(GeneralObj(ngl::Vec3 (-0.7, -3.2, 5.5), ngl::Vec3 (90,0,90), ngl::Vec3 (0.4, 0.4, 0.4), "Lavender", "assets/Lavender.obj", "textures/lavender.jpg"));         //27
     objectsVector.push_back(GeneralObj(ngl::Vec3 (-3.7, -3.9, 5.0), ngl::Vec3 (90,0,130), ngl::Vec3 (0.4, 0.4, 0.4), "Lavender", "assets/Lavender.obj", "textures/lavender.jpg"));        //28
     objectsVector.push_back(GeneralObj(ngl::Vec3 (-0.8, -2.3, 6.4), ngl::Vec3 (90,0,0), ngl::Vec3 (0.3, 0.3, 0.3), "Rose", "assets/Rose.obj", "textures/rose.jpg"));                      //29
     objectsVector.push_back(GeneralObj(ngl::Vec3 (-3.6, -3.0, 5.9), ngl::Vec3 (90,-30,20), ngl::Vec3 (0.3, 0.3, 0.3), "Rose", "assets/Rose.obj", "textures/rose.jpg"));                   //30
     objectsVector.push_back(GeneralObj(ngl::Vec3 (-1.0, -1.0, 6.3), ngl::Vec3 (90, 0, 20), ngl::Vec3 (0.4, 0.4, 0.4), "Flowers", "assets/Flowers.obj", "textures/flowers.jpg"));          //31
     objectsVector.push_back(GeneralObj(ngl::Vec3 (-4.1, -0.4, 5.8), ngl::Vec3 (90, 0, 90), ngl::Vec3 (0.4, 0.4, 0.4), "Flowers", "assets/Flowers.obj", "textures/flowers.jpg"));          //32
     m_menu.menuQuad();
     m_UI.initUI();
     m_lightTimer=startTimer(10);
     m_terrain.reset(new Terrain);
     m_terrain->initializeTerrain();
     m_text1.reset( new ngl::Text(QFont("Arial",20)));
     m_text2.reset( new ngl::Text(QFont("Arial",16)));
     m_printPtimer.reset( new ngl::Text(QFont("Arial",20)));
     m_printVtimer.reset( new ngl::Text(QFont("Arial",20)));
     m_printInstructions.reset( new ngl::Text(QFont("Arial",16)));
     m_printMenu.reset( new ngl::Text(QFont("Arial",16)));
     m_text1->setScreenSize(width(),height());
     m_text2->setScreenSize(width(),height());
     m_printPtimer->setScreenSize(width(),height());
     m_printVtimer->setScreenSize(width(),height());
     m_printMenu->setScreenSize(width(),height());
     m_printInstructions->setScreenSize(width(),height());
 }
void Window::keyPressEvent (QKeyEvent * _event) private
key press event
Definition at line 995 of file NGLScene.cpp.
References UI::decreaseExitState(), gamemenu::decreaseMenuState(), UI::exitStateSwitch(), UI::getExitFlag(), UI::getExitQuestionFlag(), gamemenu::getMenuBool(), gamemenu::getMenuState(), UI::getRestartFlag(), UI::increaseExitState(), gamemenu::increaseMenuState(), m_keysPressed, m_menu, m_UI, gamemenu::menuStateSwitch(), Pause(), Reset(), Resume(), gamemenu::setGamePlayBool(), gamemenu::setInstructionBool(), gamemenu::setMenuBool(), gamemenu::setMenuState(), and gamemenu::setUiOpen().
 {
     m_keysPressed += (Qt::Key)_event->key();
     //allows us to access the value of the menuOnOff variable, which tells me when the menu is on the screen and off the screen.
     bool m_menuOpen = m_menu.getMenuBool();
     switch (_event->key())
     {
     //escape closes the application
     case Qt::Key_Escape :m_menu.setMenuBool(true);
     m_menu.setGamePlayBool(false);
     m_menu.setInstructionBool(false); break;
     m_menu.setUiOpen(false);
     m_menu.setMenuState(0);
     //w sets to wireframe
     case Qt::Key_W : glPolygonMode(GL_FRONT_AND_BACK,GL_LINE); break;
     // S remove wireframe (back to shaded)
     case Qt::Key_S : glPolygonMode(GL_FRONT_AND_BACK,GL_FILL); break;      //Full screen mode when F key pressed
     case Qt::Key_F : showFullScreen(); break;
     //bring back from full screen mode
     case Qt::Key_P : Pause(); break;
     case Qt::Key_R : Resume(); break;
     case Qt::Key_N : Reset(); break;
     default : break;
     }
     update();
     //controls for menu
     if (m_menuOpen == true)
     {
         switch(_event->key())
         {
             case Qt::Key_Up :
             {
                 //up arrow key increases menu state, thus you go up the menu
                 m_menu.increaseMenuState();
                 break;
             }
             case Qt::Key_Down :
             {
                 //down arrow key decreases the menu state so you go down the menu
                 m_menu.decreaseMenuState();
                 break;
             }
             case Qt::Key_Return:
             {
                 //pressing return activates the menu state you have chosen, calling the function assigned to that state.
                 m_menu.menuStateSwitch();
                 if(m_menu.getMenuState() == 3)
                 {
                     //if new game is pressed, reset the game
                     Reset();
                 }
                 break;
             }
             default : break;
         }
     }
     //controls for when you lose the game and are asked to restart, same technique as the menu
     if(m_UI.getExitQuestionFlag() == true)
     {
     switch(_event->key())
     {
         case Qt::Key_Up:
         {
             m_UI.increaseExitState();
             break;
         }
         case Qt::Key_Down :
         {
             m_UI.decreaseExitState();
             break;
         }
         case Qt::Key_Return:
         {
             m_UI.exitStateSwitch();
             if(m_UI.getExitFlag() == true)
             {
                 //terminates the game.
                 QGuiApplication::exit(EXIT_SUCCESS);
             }
             if(m_UI.getRestartFlag() == true)
             {
             Reset();
             }
             break;
         }
         default : break;
         }
     }
 }
void Window::keyReleaseEvent (QKeyEvent * _event) private
function called when key is released
Definition at line 1376 of file NGLScene.cpp.
References m_keysPressed.
 {
     m_keysPressed -= (Qt::Key)_event->key();
 }
void Window::loadMatricesToShader () private
load to shader function
Load matrix function
Definition at line 278 of file NGLScene.cpp.
References M, m_cam, m_mouseGlobalTX, m_transform, MV, MVP, and normalMatrix.
 {
     ngl::ShaderLib *shader=ngl::ShaderLib::instance();
     ngl::Mat3 normalMatrix;
     ngl::Mat4 M=m_transform.getMatrix()*m_mouseGlobalTX;
     ngl::Mat4 MV=M*m_cam->getViewMatrix() ;
     ngl::Mat4 MVP = m_transform.getMatrix()*m_mouseGlobalTX*m_cam->getViewMatrix()*m_cam->getProjectionMatrix();
     normalMatrix=MV;
     normalMatrix.inverse();
     shader->setShaderParamFromMat4("MVP",MVP);
     shader->setShaderParamFromMat3("normalMatrix",normalMatrix);
 }
void Window::loadTexture () private
function to load Textures in from the texture shader
void Window::mouseMoveEvent (QMouseEvent * _event) private
mouse moved
Definition at line 914 of file NGLScene.cpp.
References m_modelPos, m_origX, m_origXPos, m_origY, m_origYPos, m_rotate, m_spinXFace, m_spinYFace, and m_translate.
 {
     //rotation and translation with mouse movements
     if(m_rotate && _event->buttons() == Qt::LeftButton)
     {
         int diffx=_event->x()-m_origX;
         int diffy=_event->y()-m_origY;
         m_spinXFace += (float) 0.5f * diffy;
         m_spinYFace += (float) 0.5f * diffx;
         m_origX = _event->x();
         m_origY = _event->y();
         update();
     }
     else if(m_translate && _event->buttons() == Qt::RightButton)
     {
         int diffX = (int)(_event->x() - m_origXPos);
         int diffY = (int)(_event->y() - m_origYPos);
         m_origXPos=_event->x();
         m_origYPos=_event->y();
         m_modelPos.m_x += INCREMENT * diffX;
         m_modelPos.m_y -= INCREMENT * diffY;
         update();
     }
 }
void Window::mousePressEvent (QMouseEvent * _event) private
mouse pressed
Definition at line 942 of file NGLScene.cpp.
References m_origX, m_origXPos, m_origY, m_origYPos, m_rotate, and m_translate.
 {
     if(_event->button() == Qt::LeftButton)
     {
         m_origX = _event->x();
         m_origY = _event->y();
         m_rotate =true;
     }
     else if(_event->button() == Qt::RightButton)
     {
         m_origXPos = _event->x();
         m_origYPos = _event->y();
         m_translate=true;
     }
 }
void Window::mouseReleaseEvent (QMouseEvent * _event) private
mouse release
Definition at line 962 of file NGLScene.cpp.
References m_rotate, and m_translate.
 {
     if (_event->button() == Qt::LeftButton)
     {
         m_rotate=false;
     }
     if (_event->button() == Qt::RightButton)
     {
         m_translate=false;
     }
 }
void Window::moveSphere () private
function that moves the player based on key inputs
function that updates the sphere position based on keys pressed
if the sphere is not colliding it moves as normal
If it is colliding return the sphere to its previous position and then continue moving normally
Definition at line 1282 of file NGLScene.cpp.
References BoundingBoxCollisions(), checkEnemyPlayerCollisions(), gamemenu::getGamePlayBool(), m_gamePlay, m_keysPressed, m_menu, m_sphere, playerIsActive, and s_sphereUpdate.
 {
     float xDirection=0.0; // x direction for the player movmement
     float zDirection=0.0; // z direction for the player movmement
     BoundingBoxCollisions();;
     //until pause works, this will stop you moving the sphere as you navigate menu
     bool m_gamePlay = m_menu.getGamePlayBool();
     if (m_gamePlay == true)
     {
         foreach(Qt::Key key, m_keysPressed)
         {
             switch (key)
             {
             //Setting the keys to the sphere controls
                 case Qt::Key_Left :  { xDirection=-s_sphereUpdate; break;}
                 case Qt::Key_Right : { xDirection=s_sphereUpdate; break;}
                 case Qt::Key_Up :    { zDirection=-s_sphereUpdate; break;}
                 case Qt::Key_Down :  { zDirection=s_sphereUpdate; break;}
                 default : break;
             }
         }
         if(m_keysPressed.size() !=0 && playerIsActive)
         {
             if (m_sphere->rotateWorld==true)
             {
                 s_sphereUpdate=0; //disables the player if a rotation is occurring
             }
             checkEnemyPlayerCollisions();
             if(m_sphere->isHit()==false)
             {
             m_sphere->move(xDirection,zDirection);
             }
             else
             {
             m_sphere->sendBack();
             m_sphere->move(xDirection,zDirection);
         }
     }
 }
 }
void Window::paintGL ()
paint function
get an instance of the shader library
set use of phong shader
set position of lights
draw scene with phong shader
prints how many items the player has picked up on the top right corner of the screen
prints a little hint on the top of the screen and the timer countdowns for the volcano eruption and plague spreading
prints in the instructions page how to get back to the menu
prints in the menu page how to navigate around it
Definition at line 756 of file NGLScene.cpp.
References Timer::counterD, cureStage, drawScene(), Timer::Dseconds, gamemenu::getInstructionBool(), gamemenu::getMenuBool(), gamemenu::getUiOpen(), ingredients, m_height, m_light, m_light2, m_light3, m_light4, m_lightPosition1, m_menu, m_printInstructions, m_printMenu, m_printPtimer, m_printVtimer, m_text1, m_text2, m_timer, m_width, Timer::minutesCountdown(), Timer::secondsCountdown(), and Timer::Vseconds.
 {
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
     glViewport(0,0,m_width,m_height);
     ngl::ShaderLib *shader=ngl::ShaderLib::instance();
     (*shader)["Phong"]->use();
     m_light->setPosition(m_lightPosition1);
     m_light->loadToShader("light1");
     m_light2->loadToShader("light2");
     m_light3->loadToShader("light3");
     m_light4->loadToShader("light4");
     drawScene("Phong");
     bool menu = m_menu.getMenuBool();
     bool instructions = m_menu.getInstructionBool();
     if (cureStage > 0 && (!menu) && (!instructions) && (m_menu.getUiOpen() == true))
     {
         m_text1->setColour(1,1,1);
         QString ingCount=QString("%1 / 4").arg(ingredients);
         m_text1->renderText(885,75,ingCount);
     }
     if((!menu) && (!instructions) && (m_menu.getUiOpen() == true))
     {
         m_text2->setColour(1,1,1);
         QString hint=QString("The plague spreads fast in such a small world...");
         m_text2->renderText(320,22,hint);
         m_printPtimer->setColour(1,1,1);
         if (m_timer->Dseconds<10 || m_timer->counterD==0 || m_timer->counterD>120)
         {
             QString plagueTimer=QString("%1 : 0%2").arg(m_timer->minutesCountdown()).arg(m_timer->secondsCountdown());
             m_printPtimer->renderText(922,690,plagueTimer);
         }
         else
         {
             QString plagueTimer=QString("%1 : %2").arg(m_timer->minutesCountdown()).arg(m_timer->secondsCountdown());
             m_printPtimer->renderText(922,690,plagueTimer);
         }
         m_printVtimer->setColour(1,1,1);
         QString volcanoTimer=QString("%1").arg(m_timer->Vseconds);
         m_printVtimer->renderText(809,690,volcanoTimer);
     }
     if((instructions))
     {
         m_printInstructions->setColour(1,1,1);
         QString instructions=QString("Press esc to go back to menu");
         m_printInstructions->renderText(360,22,instructions);
     }
     if ((menu))
     {
         m_printMenu->setColour(1,1,1);
         QString menu=QString("Use the arrowkeys to navigate the menu, press enter to select");
         m_printMenu->renderText(320,22,menu);
     }
 }
void Window::Pause () private
function to pause game
called when 'P' pressed
pauses the game
Definition at line 1385 of file NGLScene.cpp.
References m_timer, pauseEnemy, s_sphereUpdate, and Timer::setActive().
 {
     s_sphereUpdate=0;
     pauseEnemy=true;
     m_timer->setActive(false);
 }
ngl::Mat4 Window::PivotRotation (ngl::Vec3 _position, ngl::Mat4 _rotation, ngl::Vec3 _initialRotation, ngl::Vec3 _scale) private
function that will rotate objects around the centre
Parameters
[in] _position is the position of the object
[in] _rotation is the world global rotation
[in] _initialRotation is the initial rotation of the object
_scale is the scaling of the object
This function rotates an object globally around the pivot, which is at 0,0,0 It takes in the position, global rotation (which is always m_rotationCurrent), rotation of that object at the start and scale. This function returns the new transformation matrix of that object depending on the rotation of the cube.
We can use this matrix to find the new position of the object
Definition at line 299 of file NGLScene.cpp.
References scale.
 {
     ngl::Mat4 new_transformation, position_mat, pivot, scale, r;
     scale.scale(_scale.m_x, _scale.m_y, _scale.m_z);                        //setting the scale
     position_mat.translate(_position.m_x, _position.m_y, _position.m_z);    //setting the translation
     ngl::Mat4 rx; rx.rotateX(_initialRotation.m_x);
     ngl::Mat4 ry; ry.rotateY(_initialRotation.m_y);
     ngl::Mat4 rz; rz.rotateZ(_initialRotation.m_z);
     r= rx*ry*rz;                                                            //setting the rotation
     new_transformation = scale*r*position_mat*_rotation*pivot;              //creating the transformation matrix
     return new_transformation;
 }
void Window::Reset () private
function that resets when a new game is created
called when 'N' pressed
resets game
Definition at line 1406 of file NGLScene.cpp.
References bumpEnemy(), cloves, cureStage, ingredients, lavender, m_enemy, m_enemyGlobalRotation, m_enemyGlobalRotation2, m_gamePlay, m_hit, m_isAttacking, m_isAttacking2, m_isSafeFromEruption, m_menu, m_rotationCurrent, m_safeFromEruptionUiTimer, m_sphere, m_timer, m_UI, mercury, objectsVector, playerIsActive, Timer::reset(), roses, UI::setExitFlag(), UI::setExitQuestionFlag(), gamePlay::setGameErupted(), gamePlay::setGameLost(), gamemenu::setGamePlayBool(), gamePlay::setGameWon(), gamePlay::setHeartcount(), gamemenu::setInstructionBool(), gamemenu::setMenuBool(), gamemenu::setMenuState(), UI::setRestartFlag(), UI::setTriggerTimer(), and gamemenu::setUiOpen().
 {
     m_sphere->setPosition(ngl::Vec3(0,5.5,0));
     ngl::Mat4 normal;
     m_rotationCurrent=normal;
     m_enemyGlobalRotation=normal;
     m_enemyGlobalRotation2=normal;
     m_hit=0;
     playerIsActive=true;
 //-------enemy reset-----------------------------------
     m_isAttacking=false;
     m_isAttacking2=false;
     m_enemy->isReset=false; //not reset matrix yet
     m_enemy->reset();
     m_sphere->isForest=true;
     m_sphere->isGarden=false;
     bumpEnemy();
 //------------------------------------------------------
     //reset the gameloop
     m_menu.setGamePlayBool(true);
     m_menu.setMenuBool(false);
     m_menu.setInstructionBool(false);
     m_menu.setMenuState(0);
     m_menu.setUiOpen(true);
     m_gamePlay.setGameErupted(false);
     m_gamePlay.setGameWon(false);
     m_gamePlay.setGameLost(false);
     m_UI.setTriggerTimer(false);
     m_UI.setRestartFlag(false);
     m_UI.setExitQuestionFlag(false);
     m_UI.setExitFlag(false);
     // reset the volcano - timer
     m_timer->reset();
     m_isSafeFromEruption = false;
     m_safeFromEruptionUiTimer = 0;
     // reset  health
     m_gamePlay.setHeartcount(5);
     m_hit = 0;
     // reset all inventory to initial state
     cloves = false;
     lavender = false;
     mercury = false;
     roses = false;
     cureStage = 0;
     ingredients = 0;
     // reset the items' scales and redraw bounding boxes
     for (unsigned int i=0; i < objectsVector.size(); ++i)
     {
         objectsVector[i].replace();
     }
 }
void Window::resizeGL (QResizeEvent * _event)
Resizing the window
resizing window
Definition at line 62 of file NGLScene.cpp.
References m_cam, m_height, and m_width.
 {
     m_width=_event->size().width()*devicePixelRatio();
     m_height=_event->size().height()*devicePixelRatio();
     m_cam->setShape(45.0f,(float)width()/height(),0.05f,350.0f);
 }
void Window::resizeGL (int _w, int _h)
Resizing the window
resizing window
Definition at line 71 of file NGLScene.cpp.
References m_cam, m_height, and m_width.
 {
     m_cam->setShape(45.0f,(float)_w/_h,0.05f,350.0f);
     m_width=_w*devicePixelRatio();
     m_height=_h*devicePixelRatio();
 }
void Window::Resume () private
function that resumes game
called when 'R' pressed
resumes game
Definition at line 1395 of file NGLScene.cpp.
References m_timer, pauseEnemy, s_sphereUpdate, and Timer::setActive().
 {
     s_sphereUpdate=0.04;
     pauseEnemy=false;
     m_timer->setActive(true);
 }
void Window::setEnemy () private
sets all enemy movement states-being displayed either active or chasing player
Resets positions of enemies to be on the player plane.Reset rotation matrix so Garden enemies get correct position of player
Definition at line 660 of file NGLScene.cpp.
References loadMatricesToShader(), m_enemy, m_isAttacking, m_isAttacking2, m_sphere, m_transform, pauseEnemy, setEnemyRotForest(), setEnemyRotGarden(), and sphereSphereCollision().
 {
 //while grp1 is not active displays enemies inForest at their init pos while player is on other planes
   for(unsigned int i=0;i<m_enemy->enemyForest.size();i++)
   {
     if(grp1==false){
         for(unsigned int i=0;i<m_enemy->enemyForest.size();i++) //for each enemy check if player in attack radius
         {
             m_enemy->enemyForest[i].setPosition(m_enemy->enemyStartPos[i]);
             loadMatricesToShader();
             setEnemyRotForest();
         }
     }
   //while grp1 is not active displays enemies inForest at their init pos while player is on other planes
    else if(grp1==true)
    {
         m_isAttacking=false;//prevents from moving
          if(m_isAttacking==false)
          {
               loadMatricesToShader();
               setEnemyRotForest();
          }
          if(sphereSphereCollision(m_sphere->getPosition(),1.0,
                                     m_enemy->enemyForest[i].getPosition(),1.0)==true){
               m_isAttacking=true;
               if(m_enemy->enemyForest[i].isFrozen()==false && m_isAttacking==true){
               loadMatricesToShader();
               if(pauseEnemy==false){
               m_enemy->enemyForest[i].setPrey(m_sphere->getPosition());
               m_enemy->enemyForest[i].move(m_sphere->getPosition());
               m_enemy->enemyForest[i].draw();
               }
               }
              bool enemiesOverlapping=sphereSphereCollision(m_enemy->enemyForest[i].getPosition(),.9,
                                                              m_enemy->enemyForest[i+1].getPosition(),.9);
              if(enemiesOverlapping){ngl::Vec3 dir = (m_enemy->enemyForest[i].getPosition() -
                                                         m_enemy->enemyForest[i+1].getPosition());
                         m_enemy->enemyForest[i].setAvoid(dir);
             }
          }
          m_enemy->isReset=false;
      }
    }
 //----------------------------------------------------------------------------------------------------------------------
    for(unsigned int i=0;i<m_enemy->enemyGarden.size();i++) //for each enemy check if player in attack radius
    {
       m_isAttacking2=false;
       if(m_sphere->isGarden == false && m_isAttacking2 == false) //if player is not on garden plane
       {
           if(m_sphere->isForest==true)grp1=true;else grp1=false; //if player is on Forest plane, forestEnemy active
           m_enemy->isReset=false; //flag reset each time player is away from garden
           setEnemyRotGarden();
        }
        if(m_sphere->isGarden==true) //if player on garden plane
         {
             grp1=false;//deactivate forest grp, so they don't chase or display when player is not inForest
             if(m_enemy->isReset==false && grp1==false)for(int j=0;j<5;j++){
                 m_enemy->resetGarden();
             }
             if(sphereSphereCollision(m_sphere->getPosition(),1.0,
                                                m_enemy->enemyGarden[i].getPosition(),1.0) == true){ //attack radius
                 m_isAttacking2=true;
                 if (m_isAttacking2==true)
                     m_enemy->enemyGarden[i].setPrey(m_sphere->getPosition());
                     m_enemy->enemyGarden[i].move(m_sphere->getPosition());
                     setEnemyRotGarden();
                       }
              else{
                   m_isAttacking2=false;
                   m_transform.setPosition(m_enemy->enemyGarden[i].getPosition());
                   loadMatricesToShader();
                   m_enemy->enemyGarden[i].draw();
              }
               bool enemiesOverlapping=sphereSphereCollision(m_enemy->enemyGarden[i].getPosition(),.9,
                                                             m_enemy->enemyGarden[i+1].getPosition(),.9);
               if(enemiesOverlapping){ngl::Vec3 dir = (m_enemy->enemyGarden[i].getPosition() -
                                                        m_enemy->enemyGarden[i+1].getPosition());
                        m_enemy->enemyGarden[i].setAvoid(dir);
               }
           }//for plane
    }//for all
 }
void Window::setEnemyRotForest () private
resetting enemy positions after rotations
apply new rotation matrix to enemy positions
Definition at line 1342 of file NGLScene.cpp.
References loadMatricesToShader(), m_enemy, m_enemyGlobalRotation, m_transform, newEnemyRotPos, and PivotRotation().
 {
     for (unsigned int i =0;i<m_enemy->enemyForest.size();i++){
         ngl::Mat4 newEnemyMat = PivotRotation(m_enemy->enemyForest[i].getPosition(),m_enemyGlobalRotation, ngl::Vec3(0,0,0),ngl::Vec3(1,1,1));
         newEnemyRotPos.m_x = newEnemyMat.m_30;
         newEnemyRotPos.m_y = newEnemyMat.m_31;
         newEnemyRotPos.m_z = newEnemyMat.m_32;
         m_transform.setPosition(newEnemyRotPos);
         loadMatricesToShader();
         m_enemy->enemyForest[i].draw();
     }
 }
void Window::setEnemyRotGarden () private
Definition at line 1360 of file NGLScene.cpp.
References loadMatricesToShader(), m_enemy, m_enemyGlobalRotation2, m_transform, newEnemyRotPos2, and PivotRotation().
 {//rotate for both enemy vectors, does not draw if not on same plane?
     for (unsigned int i =0;i<m_enemy->enemyGarden.size();i++){
         ngl::Mat4 newEnemyMat = PivotRotation(m_enemy->enemyGarden[i].getPosition(),m_enemyGlobalRotation2, ngl::Vec3(-90,0,0),ngl::Vec3(1,1,1));
         newEnemyRotPos2.m_x = newEnemyMat.m_30;
         newEnemyRotPos2.m_y = newEnemyMat.m_31;
         newEnemyRotPos2.m_z = newEnemyMat.m_32;
         m_transform.setPosition(newEnemyRotPos2);
         loadMatricesToShader();
         m_enemy->enemyGarden[i].draw();
     }
 }
bool Window::sphereSphereCollision (ngl::Vec3 _pos1, GLfloat _radius1, ngl::Vec3 _pos2, GLfloat _radius2) private
A method to test if two spheres are colliding.
Parameters
[in] _pos1 The position of the first sphere
[in] _radius1 The radius of the first sphere
[in] _pos2 The position of the second sphere
_radius2 The radius of the second sphere
Definition at line 824 of file NGLScene.cpp.
 {
     ngl::Vec3 relPos;
     GLfloat dist;
     GLfloat minDist;
     GLfloat len;
     relPos =_pos1-_pos2;
     len=relPos.length();
     dist=len*len;
     minDist =_radius1+_radius2;
     if(dist <=(minDist * minDist))
     {
         return true;
     }
     else
     {
         return false;
     }
 }
void Window::timerEvent (QTimerEvent * event) private
timer event
Timer event to update the position of light 1 to give it some movement
timer event to update the particles with gravity
Definition at line 1094 of file NGLScene.cpp.
References lightMovementAB, lightMovementBC, lightMovementCD, lightMovementDA, m_emitter, m_gravity, m_lightPosition1, m_lightTimer, m_particleTimer, m_redrawTimer, m_updateSphereTimer, and moveSphere().
 {
     if (_event->timerId() == m_updateSphereTimer)
     {
         moveSphere();
     }
     if (_event->timerId() == m_redrawTimer)
     {
         update();
     }
     if(_event->timerId() == m_lightTimer)
     {
         if (lightMovementAB==true)
         {
             m_lightPosition1.m_x+=0.02;
             m_lightPosition1.m_z+=0.02;
             if (m_lightPosition1.m_x>=7){lightMovementBC= true ; lightMovementAB=false;}
         }
         if (lightMovementBC==true)
         {
             m_lightPosition1.m_y-=0.02;
             if (m_lightPosition1.m_y<=-7){lightMovementCD= true ; lightMovementBC=false;}
         }
         if (lightMovementCD==true)
         {
             m_lightPosition1.m_x-=0.02;
             m_lightPosition1.m_z-=0.02;
             if (m_lightPosition1.m_x<=-7){lightMovementDA= true ; lightMovementCD=false;}
         }
         if (lightMovementDA==true)
         {
             m_lightPosition1.m_y+=0.02;
             if (m_lightPosition1.m_y>=7){lightMovementAB= true ; lightMovementDA=false;}
         }
       update();
     }
     if(_event->timerId() ==   m_particleTimer)
     {
         m_emitter->update(m_gravity);
     }
 }
void Window::wheelEvent (QWheelEvent * _event) private
mouse wheel release
Definition at line 978 of file NGLScene.cpp.
References m_modelPos.
 {
     //zooming with the mouse wheel
     if(_event->delta() > 0)
     {
         m_modelPos.m_z+=ZOOM;
     }
     else if(_event->delta() <0 )
     {
         m_modelPos.m_z-=ZOOM;
     }
     update();
 }
Member Data Documentation
bool Window::cloves = m_gamePlay.clovesFlag() private
flag to show you picked up cloves
Definition at line 295 of file NGLScene.h.
ngl::Vec3 Window::cube[6][1599] private
Definition at line 369 of file NGLScene.h.
ngl::Vec3 Window::cubes[7][2] private
stores the position of the first and the last small cube on one terrain (opposite corners)
Definition at line 405 of file NGLScene.h.
int Window::cureStage = m_gamePlay.cureStage() private
variable to control quest progress
Definition at line 247 of file NGLScene.h.
int Window::ingredients = m_gamePlay.ingredients() private
variable to store how many ingredients have been picked up
Definition at line 251 of file NGLScene.h.
bool Window::lavender = m_gamePlay.lavenderFlag() private
flag to show you picked up lavender
Definition at line 283 of file NGLScene.h.
bool Window::lightMovementAB =true private
Booleans for the light movement of light1
Definition at line 299 of file NGLScene.h.
bool Window::lightMovementBC =false private
Booleans for the light movement of light1
Definition at line 303 of file NGLScene.h.
bool Window::lightMovementCD =false private
Booleans for the light movement of light1
Definition at line 307 of file NGLScene.h.
bool Window::lightMovementDA =false private
Booleans for the light movement of light1
Definition at line 311 of file NGLScene.h.
ngl::Camera* Window::m_cam private
Pointer to our camera
Definition at line 417 of file NGLScene.h.
ngl::Vec3 Window::m_cubesFirstAndLast[7][2] private
first and the last cube of one terrain (opposite corners)
Definition at line 409 of file NGLScene.h.
std::unique_ptr<Emitter> Window::m_emitter private
pointer to the emitter class
Definition at line 368 of file NGLScene.h.
std::unique_ptr<EnemyState> Window::m_enemy private
pointer to EnemyState
Definition at line 182 of file NGLScene.h.
ngl::Mat4 Window::m_enemyGlobalRotation private
rotation matrix for first enemy group
Definition at line 186 of file NGLScene.h.
ngl::Mat4 Window::m_enemyGlobalRotation2 private
rotation matrix for second enemy group
Definition at line 190 of file NGLScene.h.
int Window::m_fpsTimer private
Definition at line 263 of file NGLScene.h.
gamePlay Window::m_gamePlay private
instance of gamePlay class
Definition at line 441 of file NGLScene.h.
int Window::m_gameTimerStarterCounter private
timer that turns on the general gameplay timer e,g plague and volcano timers, else it doesn't work
Definition at line 262 of file NGLScene.h.
ngl::Mat4 Window::m_globalRotation
rotation of the world
Definition at line 76 of file NGLScene.h.
GLfloat Window::m_gravity private
gravity varibale for the particle system
Definition at line 449 of file NGLScene.h.
int Window::m_height private
height of window
Definition at line 234 of file NGLScene.h.
int Window::m_hit private
enemy-player hit count
Definition at line 202 of file NGLScene.h.
bool Window::m_isAttacking =false private
enemy Forest attack state
Definition at line 267 of file NGLScene.h.
bool Window::m_isAttacking2 =false private
enemy Garden attack state
Definition at line 271 of file NGLScene.h.
bool Window::m_isSafeFromEruption private
boolean to ask if the player is safe from eruption
Definition at line 319 of file NGLScene.h.
bool Window::m_isSafeFromEruptionTimerTriggered private
boolean to ask if the safeFromEruptionTimer is triggered
Definition at line 323 of file NGLScene.h.
QSet<Qt::Key> Window::m_keysPressed private
for the key press event
Definition at line 425 of file NGLScene.h.
ngl::Vec3 Window::m_lavenderPosition private
getting the lavender position to figure out if player is on that side
Definition at line 397 of file NGLScene.h.
std::unique_ptr<ngl::Light> Window::m_light private
unique pointer to light1
Definition at line 331 of file NGLScene.h.
std::unique_ptr<ngl::Light> Window::m_light2 private
unique pointer to light2
Definition at line 335 of file NGLScene.h.
std::unique_ptr<ngl::Light> Window::m_light3 private
unique pointer to light3
Definition at line 339 of file NGLScene.h.
std::unique_ptr<ngl::Light> Window::m_light4 private
unique pointer to light4
Definition at line 343 of file NGLScene.h.
ngl::Vec3 Window::m_lightPosition1 private
Position of light 1
Definition at line 373 of file NGLScene.h.
ngl::Vec3 Window::m_lightPosition2 private
Position of light 2
Definition at line 377 of file NGLScene.h.
ngl::Vec3 Window::m_lightPosition3 private
Position of light 3
Definition at line 381 of file NGLScene.h.
ngl::Vec3 Window::m_lightPosition4 private
Position of light 4
Definition at line 385 of file NGLScene.h.
int Window::m_lightTimer private
light timer variable
Definition at line 238 of file NGLScene.h.
gamemenu Window::m_menu private
instance of class gamemenu.
Definition at line 433 of file NGLScene.h.
std::unique_ptr<ngl::Obj> Window::m_menuBackground private
obj of our background
Definition at line 351 of file NGLScene.h.
ngl::Vec3 Window::m_modelPos private
model position
Definition at line 389 of file NGLScene.h.
ngl::Mat4 Window::m_mouseGlobalTX private
mouse transformation
Definition at line 413 of file NGLScene.h.
int Window::m_origX private
variable for mouse event
Definition at line 214 of file NGLScene.h.
int Window::m_origXPos private
variable for mouse event
Definition at line 222 of file NGLScene.h.
int Window::m_origY private
variable for mouse event
Definition at line 218 of file NGLScene.h.
int Window::m_origYPos private
variable for mouse event
Definition at line 226 of file NGLScene.h.
int Window::m_particleTimer private
Partilce timer
Definition at line 255 of file NGLScene.h.
std::unique_ptr<ngl::Text> Window::m_printInstructions private
Definition at line 363 of file NGLScene.h.
std::unique_ptr<ngl::Text> Window::m_printMenu private
Definition at line 364 of file NGLScene.h.
std::unique_ptr<ngl::Text> Window::m_printPtimer private
Definition at line 362 of file NGLScene.h.
std::unique_ptr<ngl::Text> Window::m_printVtimer private
Definition at line 361 of file NGLScene.h.
int Window::m_redrawTimer private
Definition at line 243 of file NGLScene.h.
bool Window::m_rotate private
boolean for mouse move event
Definition at line 275 of file NGLScene.h.
ngl::Mat4 Window::m_rotationCurrent
overall rotation of the world
Definition at line 80 of file NGLScene.h.
int Window::m_safeFromEruptionUiTimer private
a timer that I increment to to control how long the game draws a message for the user
Definition at line 259 of file NGLScene.h.
Space* Window::m_space private
Pointer to our space background object
Definition at line 429 of file NGLScene.h.
std::unique_ptr<Sphere> Window::m_sphere private
pointer to the player's position and cube rotation class
Definition at line 327 of file NGLScene.h.
std::unique_ptr<SphereBump> Window::m_sphereBump private
A pointer to the sphere bump
Definition at line 347 of file NGLScene.h.
int Window::m_spinXFace private
variables for mouse move event
Definition at line 206 of file NGLScene.h.
int Window::m_spinYFace private
variables for mouse move event
Definition at line 210 of file NGLScene.h.
ngl::Vec3 Window::m_spread private
Spread variable for the particles
Definition at line 401 of file NGLScene.h.
std::unique_ptr<Terrain> Window::m_terrain private
pointer to the terrain class
Definition at line 355 of file NGLScene.h.
std::unique_ptr<ngl::Text> Window::m_text1 private
instances for the on screen text printing
Definition at line 359 of file NGLScene.h.
std::unique_ptr<ngl::Text> Window::m_text2 private
Definition at line 360 of file NGLScene.h.
GLuint Window::m_textureName private
Texture name
Definition at line 445 of file NGLScene.h.
Timer* Window::m_timer
pointer to Timer class
Definition at line 72 of file NGLScene.h.
ngl::Transformation Window::m_transform private
transformation
Definition at line 421 of file NGLScene.h.
bool Window::m_translate private
boolean for mouse move event
Definition at line 279 of file NGLScene.h.
ngl::Vec3 Window::m_treePosition private
getting the tree position to figure out if player is on that side
Definition at line 393 of file NGLScene.h.
UI Window::m_UI private
instance of clas UI.
Definition at line 437 of file NGLScene.h.
int Window::m_updateSphereTimer private
timer for player movement
Definition at line 242 of file NGLScene.h.
int Window::m_width private
width of window
Definition at line 230 of file NGLScene.h.
bool Window::mercury = m_gamePlay.mercuryFlag() private
flag to show you picked up mercury
@
Definition at line 291 of file NGLScene.h.
ngl::Vec3 Window::newEnemyRotPos private
new rotation matrix for Forest enemy group
Definition at line 194 of file NGLScene.h.
ngl::Vec3 Window::newEnemyRotPos2 private
new rotation matrix for Garden enemy group
Definition at line 198 of file NGLScene.h.
std::vector<GeneralObj> Window::objectsVector
A vector to store the objects
Definition at line 68 of file NGLScene.h.
bool Window::roses = m_gamePlay.rosesFlag() private
flag to show you picked up roses
Definition at line 287 of file NGLScene.h.
int Window::Rotationtimer =0
timer for the rotation
Definition at line 84 of file NGLScene.h.
bool Window::volcanoTime private
Boolean for the volcano time
Definition at line 315 of file NGLScene.h.
The documentation for this class was generated from the following files:
NGLScene.h
NGLScene.cpp