Disaster: GeneralObj Class Reference
GeneralObj Class Reference
Simple object and bounding box loading class used to set up properties and create bounding boxes.
#include <GeneralObj.h>
Public Member Functions
GeneralObj ()
Default General Object ctor.
GeneralObj (ngl::Vec3 _objectPos, ngl::Vec3 _objectRot, ngl::Vec3 _objectScale, std::string objName, std::string objPath, std::string textPath)
General Object ctor given transformations, object name, path and texture path. Uses calcDimensions method to create a bounding box when an object is created using the min and max values of the object as extents.
ngl::Vec3 getPos ()
Get Position method returns the position of the object.
ngl::Vec3 getRotatedPos ()
Get Rotated Position method returns the position of the object after taking into account the rotation of the world.
ngl::Vec3 getRot ()
Get Rotation method returns the rotation of the object.
ngl::Vec3 getScale ()
Get Scale method returns the scale of the object.
void setPos (ngl::Vec3 _pos)
Set Position method sets _pos param to equal object position.
void setRotatedPos (ngl::Vec3 _pos)
Set Rotated Position method sets _pos param to equal object position after taking into account the rotation of the world.
void setRotatedScale (ngl::Vec3 _objectScale)
Set Rotated Scale method sets _objectScale param to equal object scale after taking into account the rotation of the world.
BBExtent getExtents ()
Get Extent method returns the extents used when creating bounding boxes for each object.
void drawObj ()
Draw Obj method draws the object to the scene.
void pickup ()
Pickup method sets the scale of the items the player interacts with to 0, making them disappear.
void replace ()
Replace method sets the scale of all the items the player may have picked up back to their original scale and puts thei bounding boxes back in used for the game reset()
void deleteBBox ()
Delete Bounding Box method sets the extents of the bounding box to 0.
Public Attributes
ngl::Vec3 initialScale
stores the initial scale of the object for the replace() method
std::unique_ptr< ngl::Obj > objPtr
pointer to Obj in NGL
Private Member Functions
void resetTransformations ()
reset Transformation method sets object position and rotation to 0 and scale to 1
void loadMatricesToShader ()
Loads matrices to shader.
void setExtents ()
Sets the extents of the bounding box to equal the min and max values of the object in the x, y and z axes. Calculates the min and max values of the bounding box by dividing the width, height and depth by 2 and adding/subtracting the value from the object position.
Private Attributes
ngl::Vec3 m_objectPos
The object position.
ngl::Vec3 m_rotatedObjectPos
The object position after taking into account the rotation of the world.
ngl::Vec3 m_rotatedObjectScale
The object scale after taking into account the rotation of the world.
ngl::Vec3 m_scaledBBoxDimensions
The extents of the bounding box after taking into account the new scale of the objects.
ngl::Vec3 m_objectRot
The object rotation.
ngl::Vec3 m_objectScale
The object scale.
std::string m_path
The path to the obj file of the objects.
std::string m_tex
The path to the texture file for the objects.
std::string m_name
The name of the object.
ngl::Transformation m_transform
An NGL transformation attribute.
BBExtent m_bbExtents
A Bounding Box Extents object to store the new extents of the bounding boxes.
Detailed Description
Simple object and bounding box loading class used to set up properties and create bounding boxes.
Author
Ruth Hutton
Version
1.0
Date
Last Revision 08/05/17 A function to delete the bounding boxes added
Definition at line 20 of file GeneralObj.h.
Constructor & Destructor Documentation
GeneralObj::GeneralObj ()
Default General Object ctor.
Definition at line 5 of file GeneralObj.cpp.
References resetTransformations().
 {
     // set the object transformations to 0
     resetTransformations();
 }
GeneralObj::GeneralObj (ngl::Vec3 _objectPos, ngl::Vec3 _objectRot, ngl::Vec3 _objectScale, std::string objName, std::string objPath, std::string textPath)
General Object ctor given transformations, object name, path and texture path. Uses calcDimensions method to create a bounding box when an object is created using the min and max values of the object as extents.
Parameters
[in] _objectPos the position of the object.
[in] _objectRot the rotation of the object.
[in] _objectScale the scale of the object.
[in] objName the given name of the object.
[in] objPath the path to the object file.
[in] textPath the path to the texture for the object.
Definition at line 13 of file GeneralObj.cpp.
References initialScale, m_name, m_objectPos, m_objectRot, m_objectScale, m_path, m_rotatedObjectPos, m_rotatedObjectScale, m_tex, objPtr, and resetTransformations().
 {
     resetTransformations();
     m_objectPos = _objectPos;
     m_objectRot = _objectRot;
     m_objectScale = _objectScale;
     m_path = objPath;
     m_name = objName;
     m_tex = textPath;
     // Create a new ngl object using the path of the Obj files and their textures
     objPtr.reset(new ngl::Obj(objPath,textPath));
     objPtr->createVAO();
     // Set up the bounding box and center
     objPtr->calcDimensions();
     // The object position and scale must take into account the rotation of the sphere
     m_rotatedObjectPos = m_objectPos;
     m_rotatedObjectScale = m_objectScale;
     // Store the scale of the objects in a different variable so it can be accessed later in the replace() function
     initialScale = m_objectScale;
 }
Member Function Documentation
void GeneralObj::deleteBBox ()
Delete Bounding Box method sets the extents of the bounding box to 0.
Definition at line 116 of file GeneralObj.cpp.
References m_rotatedObjectScale.
 {
     // set the object scale to 0 causing the bounding box extents to also be set to 0
     m_rotatedObjectScale.m_x = 0;
     m_rotatedObjectScale.m_y = 0;
     m_rotatedObjectScale.m_z = 0;
 }
void GeneralObj::drawObj ()
Draw Obj method draws the object to the scene.
Definition at line 41 of file GeneralObj.cpp.
References objPtr, and setExtents().
 {
     setExtents();
     // draw the objects to the scene
     objPtr->draw();
 }
BBExtent GeneralObj::getExtents () inline
Get Extent method returns the extents used when creating bounding boxes for each object.
Definition at line 82 of file GeneralObj.h.
References m_bbExtents.
 {return m_bbExtents;}
ngl::Vec3 GeneralObj::getPos () inline
Get Position method returns the position of the object.
Definition at line 42 of file GeneralObj.h.
References m_objectPos.
 {return m_objectPos;}
ngl::Vec3 GeneralObj::getRot () inline
Get Rotation method returns the rotation of the object.
Definition at line 50 of file GeneralObj.h.
References m_objectRot.
 {return m_objectRot;}
ngl::Vec3 GeneralObj::getRotatedPos () inline
Get Rotated Position method returns the position of the object after taking into account the rotation of the world.
Definition at line 46 of file GeneralObj.h.
References m_rotatedObjectPos.
 {return m_rotatedObjectPos;}
ngl::Vec3 GeneralObj::getScale () inline
Get Scale method returns the scale of the object.
Definition at line 59 of file GeneralObj.h.
References m_objectScale.
 {return m_objectScale;}
void GeneralObj::loadMatricesToShader () private
Loads matrices to shader.
void GeneralObj::pickup ()
Pickup method sets the scale of the items the player interacts with to 0, making them disappear.
Author
Caterina Malfe
Definition at line 107 of file GeneralObj.cpp.
References deleteBBox(), and m_objectScale.
 {
     // set the scale of the object and its bounding box to zero
     m_objectScale = ngl::Vec3 (0,0,0);
     deleteBBox();
 }
void GeneralObj::replace ()
Replace method sets the scale of all the items the player may have picked up back to their original scale and puts thei bounding boxes back in used for the game reset()
Author
Caterina Malfe'
Definition at line 126 of file GeneralObj.cpp.
References initialScale, m_objectScale, and m_rotatedObjectScale.
 {
     // rescales all the objects and their bounding boxes to their original scale
     m_objectScale = initialScale;
     m_rotatedObjectScale = initialScale;
 }
void GeneralObj::resetTransformations () private
reset Transformation method sets object position and rotation to 0 and scale to 1
Definition at line 79 of file GeneralObj.cpp.
References m_objectPos, m_objectRot, m_objectScale, m_rotatedObjectPos, and m_rotatedObjectScale.
 {
     // set position and rotation of the objects to 0
     // set the object scale to 1
     m_objectPos.m_x = 0;
     m_objectPos.m_y = 0;
     m_objectPos.m_z = 0;
     m_objectRot.m_x = 0;
     m_objectRot.m_y = 0;
     m_objectRot.m_z = 0;
     m_objectScale.m_x = 1;
     m_objectScale.m_y = 1;
     m_objectScale.m_z = 1;
     m_rotatedObjectPos.m_x = 0;
     m_rotatedObjectPos.m_y = 0;
     m_rotatedObjectPos.m_z = 0;
     m_rotatedObjectScale.m_x = 1;
     m_rotatedObjectScale.m_y = 1;
     m_rotatedObjectScale.m_z = 1;
 }
void GeneralObj::setExtents () private
Sets the extents of the bounding box to equal the min and max values of the object in the x, y and z axes. Calculates the min and max values of the bounding box by dividing the width, height and depth by 2 and adding/subtracting the value from the object position.
Definition at line 50 of file GeneralObj.cpp.
References BBExtent::BBdepth, BBExtent::BBheight, BBExtent::BBwidth, m_bbExtents, m_rotatedObjectPos, m_rotatedObjectScale, m_scaledBBoxDimensions, BBExtent::maxX, BBExtent::maxY, BBExtent::maxZ, BBExtent::minX, BBExtent::minY, BBExtent::minZ, and objPtr.
 {
     // Create a temporary bounding box to access the properties of all bounding boxes in the scene
     ngl::BBox tmpBB(objPtr->getBBox());
     // Multiply the dimensions of the bounding boxes by the new scale values
     // to access the scaled height, width and depth values
     m_scaledBBoxDimensions.m_y = (tmpBB.height())*(m_rotatedObjectScale.m_y);
     m_scaledBBoxDimensions.m_x = (tmpBB.width())*(m_rotatedObjectScale.m_x);
     m_scaledBBoxDimensions.m_z = (tmpBB.depth())*(m_rotatedObjectScale.m_z);
     // Divide the dimensions by 2 to access the lengths in each axes from the center of the object
     m_bbExtents.BBheight = (m_scaledBBoxDimensions.m_y)/2.0f;
     m_bbExtents.BBwidth = (m_scaledBBoxDimensions.m_x)/2.0f;
     m_bbExtents.BBdepth = (m_scaledBBoxDimensions.m_z)/2.0f;
     // Use the calculated lengths from the object center to calculate the min and max values for the
     // bounding boxes
     m_bbExtents.minX = m_rotatedObjectPos.m_x - m_bbExtents.BBwidth;
     m_bbExtents.minY = m_rotatedObjectPos.m_y - m_bbExtents.BBheight;
     m_bbExtents.minZ = m_rotatedObjectPos.m_z - m_bbExtents.BBdepth;
     m_bbExtents.maxX = m_rotatedObjectPos.m_x + m_bbExtents.BBwidth;
     m_bbExtents.maxY = m_rotatedObjectPos.m_y + m_bbExtents.BBheight;
     m_bbExtents.maxZ = m_rotatedObjectPos.m_z + m_bbExtents.BBdepth;
 }
void GeneralObj::setPos (ngl::Vec3 _pos) inline
Set Position method sets _pos param to equal object position.
Parameters
[in] _pos the object position
Definition at line 64 of file GeneralObj.h.
References m_objectPos.
 { m_objectPos = _pos; }
void GeneralObj::setRotatedPos (ngl::Vec3 _pos) inline
Set Rotated Position method sets _pos param to equal object position after taking into account the rotation of the world.
Parameters
[in] _pos the object position
Definition at line 69 of file GeneralObj.h.
References m_rotatedObjectPos.
 { m_rotatedObjectPos = _pos; }
void GeneralObj::setRotatedScale (ngl::Vec3 _objectScale) inline
Set Rotated Scale method sets _objectScale param to equal object scale after taking into account the rotation of the world.
Definition at line 73 of file GeneralObj.h.
References m_rotatedObjectScale.
 { m_rotatedObjectScale = _objectScale; }
Member Data Documentation
ngl::Vec3 GeneralObj::initialScale
stores the initial scale of the object for the replace() method
Author
Caterina Malfe'
Definition at line 55 of file GeneralObj.h.
BBExtent GeneralObj::m_bbExtents private
A Bounding Box Extents object to store the new extents of the bounding boxes.
Definition at line 162 of file GeneralObj.h.
std::string GeneralObj::m_name private
The name of the object.
Definition at line 154 of file GeneralObj.h.
ngl::Vec3 GeneralObj::m_objectPos private
The object position.
Definition at line 122 of file GeneralObj.h.
ngl::Vec3 GeneralObj::m_objectRot private
The object rotation.
Definition at line 138 of file GeneralObj.h.
ngl::Vec3 GeneralObj::m_objectScale private
The object scale.
Definition at line 142 of file GeneralObj.h.
std::string GeneralObj::m_path private
The path to the obj file of the objects.
Definition at line 146 of file GeneralObj.h.
ngl::Vec3 GeneralObj::m_rotatedObjectPos private
The object position after taking into account the rotation of the world.
Definition at line 126 of file GeneralObj.h.
ngl::Vec3 GeneralObj::m_rotatedObjectScale private
The object scale after taking into account the rotation of the world.
Definition at line 130 of file GeneralObj.h.
ngl::Vec3 GeneralObj::m_scaledBBoxDimensions private
The extents of the bounding box after taking into account the new scale of the objects.
Definition at line 134 of file GeneralObj.h.
std::string GeneralObj::m_tex private
The path to the texture file for the objects.
Definition at line 150 of file GeneralObj.h.
ngl::Transformation GeneralObj::m_transform private
An NGL transformation attribute.
Definition at line 158 of file GeneralObj.h.
std::unique_ptr<ngl::Obj> GeneralObj::objPtr
pointer to Obj in NGL
Definition at line 77 of file GeneralObj.h.
The documentation for this class was generated from the following files:
GeneralObj.h
GeneralObj.cpp