Disaster: gamemenu Class Reference
gamemenu Class Reference
#include <GameMenu.h>
Public Member Functions
gamemenu ()
class constructor
void drawQuad (int _texID)
draws a quad
void menuQuad ()
initiates the quad that is drawn for menu items
void playGame ()
sets variables to allow the game to start/draw
void instructions (int _texID)
draws instruction screen
void newGame ()
sets variables to create a new game
void exit ()
exit game
void drawMenu ()
draws the menu quads/buttons to the screen
void menuButtonScaling ()
increases/decreases button scales depending on the menu state
void increaseMenuState ()
increases the menu state
void decreaseMenuState ()
decreases menu state
void menuStateSwitch ()
changes what functions will be called when menu state is changed in game
const bool & getMenuBool () const
gets the menu bool from class object
void setMenuBool (bool bool_)
sets if the menu is open
const bool & getGamePlayBool () const
void setGamePlayBool (bool gamebool_)
gets bool which states if gameplay is drawn
const bool & getInstructionBool () const
gets if intsruction menu is open
void setInstructionBool (bool instructionBool_)
sets if the instructions are drawn
void loadMatricesToMenuShader ()
method to load transform matrices to shader.
void drawInstructions ()
draws all the quads to create the UI
int getMenuState () const
gets value of menu state
void setMenuState (int _menustate)
sets value of menu state
bool getUiOpen () const
gets if the Ui is open
void setUiOpen (bool _UiOpen)
sets whether the Ui is open
Private Attributes
int m_buttonScale1
scales button 1
int m_buttonScale2
scales button 2
int m_buttonScale3
scales button 3
int m_buttonScale4
scales button 4
int m_mstate
value for menu state, controls what button you are going to select and what function will be called due to this value.
bool m_UiOpen
if the UI is open or not, used to stop UI being drawn during menu, instructions and game win/lose screens.
bool m_menuFlag
flag to tell me when the menu is op, true = open, false = closed
bool m_gameFlag
flag to tell me when the game is playing or not.
bool m_instructionsFlag
flag to tell me if intsructions should be drawn
std::unique_ptr
< ngl::VertexArrayObject > m_UIQuad
object of the UI quad
std::vector< GLint > m_menuTextureId
texture ID
ngl::Transformation m_menuTransform
instance of ngl class for transformations on VAOs
Detailed Description
Definition at line 16 of file GameMenu.h.
Constructor & Destructor Documentation
gamemenu::gamemenu ()
class constructor
Definition at line 11 of file GameMenu.cpp.
References m_gameFlag, m_instructionsFlag, m_menuFlag, m_mstate, and m_UiOpen.
 {
     //initiate variables
     m_menuFlag = true;
     m_gameFlag = true;
     m_instructionsFlag = false;
     m_mstate = 0;
     m_UiOpen = false;
 }
Member Function Documentation
void gamemenu::decreaseMenuState ()
decreases menu state
Definition at line 307 of file GameMenu.cpp.
References m_mstate.
 {
     if (m_mstate> 0)
     {
         m_mstate --;
     }
 }
void gamemenu::drawInstructions ()
draws all the quads to create the UI
Definition at line 342 of file GameMenu.cpp.
References drawQuad(), instructions(), loadMatricesToMenuShader(), and m_menuTransform.
 {
     m_menuTransform.reset();
     m_menuTransform.setPosition(0.0,0.5,0.0);
     m_menuTransform.setScale(5.0, 5.0, 1.0);
     loadMatricesToMenuShader();
     drawQuad(0);
     m_menuTransform.reset();
     m_menuTransform.setPosition(0.0,0.0,-0.1);
     m_menuTransform.setScale(1.5, 1.5, 1.0);
     loadMatricesToMenuShader();
     instructions(5);
 }
void gamemenu::drawMenu ()
draws the menu quads/buttons to the screen
Definition at line 188 of file GameMenu.cpp.
References drawQuad(), loadMatricesToMenuShader(), m_buttonScale1, m_buttonScale2, m_buttonScale3, m_buttonScale4, m_menuTransform, and menuButtonScaling().
 {
      //calls function to adjust the scaling sizes of buttons
      menuButtonScaling();
      //Creating the menu
      //transforms the position onto the screen
      m_menuTransform.reset();
      m_menuTransform.setPosition(0.0,0.5,0.0);
      m_menuTransform.setScale(5.0, 5.0, 1.0);
      //load matrices to the shader
      loadMatricesToMenuShader();
      //draw the quad
      drawQuad(0);
      m_menuTransform.reset();
      m_menuTransform.setPosition(-0.7, 0.8, -0.1);
      m_menuTransform.setScale(0.3 * m_buttonScale4, 0.3 * m_buttonScale4, 1.0);
      loadMatricesToMenuShader();
      drawQuad(1);
      m_menuTransform.reset();
      m_menuTransform.setPosition(-0.7, 0.3, -0.1);
      m_menuTransform.setScale(0.3 * m_buttonScale1, 0.3 * m_buttonScale1, 1.0);
      loadMatricesToMenuShader();
      drawQuad(2);
      m_menuTransform.reset();
      m_menuTransform.setPosition(-0.7, -0.3, -0.1);
      m_menuTransform.setScale(0.3 * m_buttonScale2, 0.3 * m_buttonScale2, 0.0);
      loadMatricesToMenuShader();
      drawQuad(3);
      m_menuTransform.reset();
      m_menuTransform.setPosition(-0.7, -0.8,-0.1);
      m_menuTransform.setScale(0.3 * m_buttonScale3, 0.3 * m_buttonScale3, 0.0);
      loadMatricesToMenuShader();
      drawQuad(4);
 }
void gamemenu::drawQuad (int _texID)
draws a quad
Parameters
[in] texture ID
Definition at line 86 of file GameMenu.cpp.
References m_menuTextureId, and m_UIQuad.
 {
     ngl::ShaderLib *shader=ngl::ShaderLib::instance();
     glEnable(GL_BLEND);
     glEnable(GL_ALPHA);
     glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
     (*shader)["UI"]->use();
     glBindTexture(GL_TEXTURE_2D,m_menuTextureId[_texID]);
     m_UIQuad->bind();
     m_UIQuad->draw();
     m_UIQuad->unbind();
     glDisable(GL_BLEND);
 }
void gamemenu::exit ()
exit game
Definition at line 277 of file GameMenu.cpp.
                    {
     //terminates the game.
     QGuiApplication::exit(EXIT_SUCCESS);
 }
const bool& gamemenu::getGamePlayBool () const inline
Definition at line 82 of file GameMenu.h.
References m_gameFlag.
 { return m_gameFlag;}
const bool& gamemenu::getInstructionBool () const inline
gets if intsruction menu is open
Returns
returns if menu is open
Definition at line 92 of file GameMenu.h.
References m_instructionsFlag.
 { return m_instructionsFlag;}
const bool& gamemenu::getMenuBool () const inline
gets the menu bool from class object
Parameters
[out] returns the flag that gives if the menu is open (drawn to screen)
Definition at line 73 of file GameMenu.h.
References m_menuFlag.
 { return m_menuFlag;}
int gamemenu::getMenuState () const
gets value of menu state
Definition at line 373 of file GameMenu.cpp.
References m_mstate.
 {
     return m_mstate;
 }
bool gamemenu::getUiOpen () const
gets if the Ui is open
Definition at line 359 of file GameMenu.cpp.
References m_UiOpen.
 {
     return m_UiOpen;
 }
void gamemenu::increaseMenuState ()
increases the menu state
Definition at line 297 of file GameMenu.cpp.
References m_mstate.
 {
     if (m_mstate < 3)
     {
         m_mstate ++;
     }
 }
void gamemenu::instructions (int _texID)
draws instruction screen
Parameters
[in] texture ID
Definition at line 250 of file GameMenu.cpp.
References m_gameFlag, m_instructionsFlag, m_menuFlag, m_menuTextureId, m_UiOpen, and m_UIQuad.
{
     //loads up a screen showing the instructions for the game
     //setting variables
     m_gameFlag = false;
     m_menuFlag = false;
     m_UiOpen = false;
     m_instructionsFlag = true;
     ngl::ShaderLib *shader=ngl::ShaderLib::instance();
     glEnable (GL_BLEND);
     glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
     //choose shader
     (*shader)["UI"]->use();
     glBindTexture(GL_TEXTURE_2D,m_menuTextureId[_texID]);
     m_UIQuad->bind();
     m_UIQuad->draw();
     m_UIQuad->unbind();
 }
void gamemenu::loadMatricesToMenuShader ()
method to load transform matrices to shader.
Definition at line 285 of file GameMenu.cpp.
References m_menuTransform, and scale.
 {
     ngl::ShaderLib *shader=ngl::ShaderLib::instance();
     (*shader)["UI"]->use();
     ngl::Vec3 position = m_menuTransform.getPosition();
     ngl::Vec3 scale = m_menuTransform.getScale();
     shader->setRegisteredUniform("pos", position);
     shader->setRegisteredUniform("scale", scale);
 }
void gamemenu::menuButtonScaling ()
increases/decreases button scales depending on the menu state
Definition at line 107 of file GameMenu.cpp.
References m_buttonScale1, m_buttonScale2, m_buttonScale3, m_buttonScale4, and m_mstate.
 {
     //set menu buttons to a scale of 1
     m_buttonScale1 = 1;
     m_buttonScale2 = 1;
     m_buttonScale3 = 1;
     m_buttonScale4 = 1;
     //switch statement, changed when the user wants to go up and down the menu buttons
     switch(m_mstate)
     {
     case 3:
         //adjusting the scaling by adding and subtracting to the values, only if theyre within certain bounds
         //to prevent the scaling to increase/decrease too much or at the wrong times
         if (m_buttonScale1 >= 2)
        {
            m_buttonScale1 = m_buttonScale1 - 1;
        }
        else if (m_buttonScale4 < 2)
        {
            m_buttonScale4 = m_buttonScale4 + 1;
        }
        break;
     case 2:
         if(m_buttonScale1 < 2)
         {
             m_buttonScale1 = m_buttonScale1 + 1;
         }
         else if (m_buttonScale2 >= 2)
         {
             m_buttonScale2 = m_buttonScale2 - 1;
         }
         else if( m_buttonScale4 >= 2)
         {
             m_buttonScale4 = m_buttonScale4 -1;
         }
         break;
     case 1:
         if (m_buttonScale2 < 2)
         {
             m_buttonScale2 = m_buttonScale2 + 1;
         }
         else if (m_buttonScale3 >= 2)
         {
             m_buttonScale3 = m_buttonScale3 - 1;
         }
         else if (m_buttonScale1 >= 2)
         {
             m_buttonScale1 = m_buttonScale1 - 1;
         }
         break;
     case 0:
          if (m_buttonScale2 >= 2)
         {
             m_buttonScale2 = m_buttonScale2 - 1;
         }
         else if (m_buttonScale3 < 2)
         {
             m_buttonScale3 = m_buttonScale3 + 1;
         }
         break;
     }
 }
void gamemenu::menuQuad ()
initiates the quad that is drawn for menu items
Definition at line 23 of file GameMenu.cpp.
References m_menuTextureId, and m_UIQuad.
{
     //creating a vector of strings to store IDs of textures
     std::vector<std::string> m_menuTextures;
     m_menuTextures.push_back("textures/Galaxy.tif");
     m_menuTextures.push_back("textures/menu_UI_Textures/newGame.png");
     m_menuTextures.push_back("textures/menu_UI_Textures/playgame2.png");
     m_menuTextures.push_back("textures/menu_UI_Textures/instructions2.png");
     m_menuTextures.push_back("textures/menu_UI_Textures/ExitGame2.png");
     m_menuTextures.push_back("textures/menu_UI_Textures/instructions_Page.png");
     //storing the IDs into vector
     for (unsigned int i = 0; i < m_menuTextures.size(); i++)
     {
         ngl::Texture m_menuTex(m_menuTextures[i]);
         //ID for texture
         GLint texID = m_menuTex.setTextureGL();
         m_menuTextureId.push_back(texID);
     }
     //creating the quad for the UI using a vertex array object
     m_UIQuad.reset(ngl::VertexArrayObject::createVOA(GL_TRIANGLES));
     m_UIQuad->bind();
     //shared vertices
     const static GLubyte indices[]=  {
                                          0, 1, 3,   //first triangle
                                          1, 2, 3   //second triangle
                                       };
     //Vertices of the quad
     GLfloat vertices[] = {
                               0.5f,  0.5f, 0.0f,
                               0.5f, -0.5f, 0.0f,
                               -0.5f, -0.5f, 0.0f,
                               -0.5f,  0.5f, 0.0f,
                           };
     //Uvs of the quad
      GLfloat uv[]={
                        1.0f, 1.0f,
                        1.0f, 0.0f,
                        0.0f, 0.0f,
                        0.0f, 1.0f,
                    };
     // in this case we are going to set our data as the vertices above
     m_UIQuad->setIndexedData(12*sizeof(GLfloat),vertices[0],sizeof(indices),&indices[0],GL_UNSIGNED_BYTE,GL_STATIC_DRAW);
     // now we set the attribute pointer to be 0 (as this matches vertIn in our shader)
     m_UIQuad->setVertexAttributePointer(0,3,GL_FLOAT,0,0);
     m_UIQuad->setIndexedData(8*sizeof(GLfloat),uv[0],sizeof(indices),&indices[0],GL_UNSIGNED_BYTE,GL_STATIC_DRAW);
     // now we set the attribute pointer to be 0 (as this matches vertIn in our shader)
     m_UIQuad->setVertexAttributePointer(1,2,GL_FLOAT,0,0); //bind verts to shader
     m_UIQuad->setNumIndices(sizeof(indices));
     // now unbind
     m_UIQuad->unbind();
 }
void gamemenu::menuStateSwitch ()
changes what functions will be called when menu state is changed in game
Definition at line 317 of file GameMenu.cpp.
References exit(), instructions(), m_mstate, newGame(), and playGame().
 {
     //when the player presses enter, this will be called and depending on the menu state a function will be called.
     switch(m_mstate)
     {
         case 3 :
         newGame();
         break;
         case 2 :
         playGame();
         break;
         case 1 :
         instructions(5);
         break;
         case 0 :
         exit();
         break;
      }
 }
void gamemenu::newGame ()
sets variables to create a new game
Definition at line 241 of file GameMenu.cpp.
References m_gameFlag, m_menuFlag, and m_UiOpen.
 {
     m_gameFlag = true;
     m_UiOpen = true;
     m_menuFlag = false;
 }
void gamemenu::playGame ()
sets variables to allow the game to start/draw
Definition at line 231 of file GameMenu.cpp.
References m_gameFlag, m_menuFlag, and m_UiOpen.
 {
     //sets the booleans to control what is drawn to the screen
     m_gameFlag = true;
     m_menuFlag = false;
     m_UiOpen = true;
 }
void gamemenu::setGamePlayBool (bool gamebool_) inline
gets bool which states if gameplay is drawn
Parameters
[in] sets gameplay bool to true if gameplay is to be drawn, false if not drawn
Definition at line 87 of file GameMenu.h.
References m_gameFlag.
 {m_gameFlag = gamebool_;}
void gamemenu::setInstructionBool (bool instructionBool_) inline
sets if the instructions are drawn
Parameters
[in] instruction bool, if true menu is drawn
Definition at line 97 of file GameMenu.h.
References m_instructionsFlag.
 {m_instructionsFlag = instructionBool_;}
void gamemenu::setMenuBool (bool bool_) inline
sets if the menu is open
Parameters
[in] boolean,if menuFlag = true menu is open, if false menu is not open
Definition at line 78 of file GameMenu.h.
References m_menuFlag.
 {m_menuFlag=bool_;}
void gamemenu::setMenuState (int _menustate)
sets value of menu state
Parameters
[in] menustate which is the menu state variable
Definition at line 380 of file GameMenu.cpp.
References m_mstate.
 {
     m_mstate = _menustate;
 }
void gamemenu::setUiOpen (bool _UiOpen)
sets whether the Ui is open
Parameters
[in] boolean to control if the UI is open, true is open.
Definition at line 366 of file GameMenu.cpp.
References m_UiOpen.
 {
     m_UiOpen = _UiOpen;
 }
Member Data Documentation
int gamemenu::m_buttonScale1 private
scales button 1
Definition at line 130 of file GameMenu.h.
int gamemenu::m_buttonScale2 private
scales button 2
Definition at line 134 of file GameMenu.h.
int gamemenu::m_buttonScale3 private
scales button 3
Definition at line 138 of file GameMenu.h.
int gamemenu::m_buttonScale4 private
scales button 4
Definition at line 142 of file GameMenu.h.
bool gamemenu::m_gameFlag private
flag to tell me when the game is playing or not.
Definition at line 158 of file GameMenu.h.
bool gamemenu::m_instructionsFlag private
flag to tell me if intsructions should be drawn
Definition at line 162 of file GameMenu.h.
bool gamemenu::m_menuFlag private
flag to tell me when the menu is op, true = open, false = closed
Definition at line 154 of file GameMenu.h.
std::vector<GLint> gamemenu::m_menuTextureId private
texture ID
Definition at line 170 of file GameMenu.h.
ngl::Transformation gamemenu::m_menuTransform private
instance of ngl class for transformations on VAOs
Definition at line 174 of file GameMenu.h.
int gamemenu::m_mstate private
value for menu state, controls what button you are going to select and what function will be called due to this value.
Definition at line 146 of file GameMenu.h.
bool gamemenu::m_UiOpen private
if the UI is open or not, used to stop UI being drawn during menu, instructions and game win/lose screens.
Definition at line 150 of file GameMenu.h.
std::unique_ptr<ngl::VertexArrayObject> gamemenu::m_UIQuad private
object of the UI quad
Definition at line 166 of file GameMenu.h.
The documentation for this class was generated from the following files:
GameMenu.h
GameMenu.cpp