Disaster: Enemy Class Reference
Enemy Class Reference
This class is in charge of calculating the enemy movement using predetor behaviour models similar to Craig Reynold's'Boids' algorithms.
#include <Enemy.h>
Public Member Functions
Enemy (ngl::Vec3 _pos)
ctr
void move (const ngl::Vec3 &_playerPos)
methods to initially draw the enemy at creation time
void draw ()
methods to draw the enemies
ngl::Vec3 getPosition ()
inline functions to get the position of enemy
void setPosition (ngl::Vec3 _pos)
inline functions to set the position of enemy
void setPrey (const ngl::Vec3 &_playerPos)
method to calculate the distance between the prey and enemy
void setHit (bool _h, int _hitCount)
methods to check if enemy has collided with player
void setAvoid (ngl::Vec3 _dir)
method to set avoidance force whenever enemies are about to overlap each other
void freezeEnemy ()
forces enemy to stop chasing player whenever out of bounds
bool isFrozen ()
checks if current enemy is inactive/frozen
Private Member Functions
float distanceCalc (ngl::Vec3 _a, ngl::Vec3 _b)
function to calculate distance between player and enemy
void updatePosition ()
combines all the behaviours and updates the enemy positions
void setChase (ngl::Vec3 _pos, float _targetSpeed)
function to set the goal of the enemies
void setTarget ()
function to set the target of the enemies
void enemyFreeze ()
function to freeze the movement of the enemies
void fleeWalls ()
function to stop the enemies from going out of bounds
void setSteer ()
function to set the steering behavour of the enemies
void printPos ()
function to check the current positions of the enemies
used for debugging
Private Attributes
bool m_hit =false
int m_hitCount
bool isAvoiding =true
flag if enemy is using avoidance force
bool m_behaviour =true
flag if enemy is using behaviour forces
bool m_isFrozen
flag if enemy has gone over bounds and is not moving
bool preyIsActive
flag check if prey is set
ngl::Vec3 m_dir
forces to calculate behaviors for enemies
ngl::Vec3 m_prey
ngl::Vec3 m_flee
ngl::Vec3 m_target
ngl::Vec3 m_steering
ngl::Vec3 m_velocity
ngl::Vec3 desiredVelocity
ngl::Vec3 m_goal
ngl::Vec3 m_avoid
ngl::Vec3 m_separate
ngl::Vec3 m_pos
enemy position
float m_prevDistance
relevant weights applied to forces
float m_speed
float m_maxAccelerate
float m_randAccel
float m_xmax
float m_xmin
float m_zmax
float m_zmin
float m_maxSpeed
float m_minSpeed
float m_avoidWeight
Detailed Description
This class is in charge of calculating the enemy movement using predetor behaviour models similar to Craig Reynold's'Boids' algorithms.
Author
Stiliana Gospodinova
Version
1.0
09/10/17
Definition at line 17 of file Enemy.h.
Constructor & Destructor Documentation
Enemy::Enemy (ngl::Vec3 _pos)
ctr
Enemy class handling calculations for enemy behaviour forces
_pos initial enemy position passed in
Definition at line 9 of file Enemy.cpp.
References m_avoidWeight, m_maxAccelerate, m_maxSpeed, m_minSpeed, m_pos, m_speed, m_velocity, and preyIsActive.
 {
     m_pos=_pos;
     preyIsActive=false;
     m_speed=.5;
     m_maxAccelerate=0.03;
     m_velocity.set(1,0.3,1.2);
     m_maxSpeed=1.0;
     m_minSpeed=0.2;
     m_avoidWeight=0.2;
 }
Member Function Documentation
float Enemy::distanceCalc (ngl::Vec3 _a, ngl::Vec3 _b) private
function to calculate distance between player and enemy
Parameters
[in] _a position of player
_b position of enemy
Definition at line 86 of file Enemy.cpp.
 {
     return sqrt(((a.m_x - b.m_x)*(a.m_x - b.m_x) + (a.m_z - b.m_z)*(a.m_z - b.m_z)));
 }
void Enemy::draw ()
methods to draw the enemies
Definition at line 74 of file Enemy.cpp.
References m_hit.
 {
     ngl::ShaderLib *shader=ngl::ShaderLib::instance();
     if(m_hit)
     shader->setUniform("Colour",1.0f,0.0f,0.0f);
     else
     shader->setUniform("Colour",0.0f,0.0f,1.0f);
     ngl::VAOPrimitives::instance()->draw("Enemy");
 }
void Enemy::enemyFreeze () private
function to freeze the movement of the enemies
void Enemy::fleeWalls () private
function to stop the enemies from going out of bounds
Definition at line 91 of file Enemy.cpp.
References freezeEnemy(), m_behaviour, m_isFrozen, m_pos, and printPos().
 {
     m_behaviour=true;
     //edit
     if(m_pos.m_x<=-4.8 || m_pos.m_x>=4.8)
     {
         std::cout<<"OOBx";
         m_isFrozen=true;
         m_behaviour=false;
         freezeEnemy();
         printPos();
     }
     if(m_pos.m_z<=-4.8 || m_pos.m_z>=4.8)
     {
         std::cout<<"OOBy";
         m_isFrozen=true;
         m_behaviour=false;
         freezeEnemy();
         printPos();
     }
 }
void Enemy::freezeEnemy ()
forces enemy to stop chasing player whenever out of bounds
Definition at line 174 of file Enemy.cpp.
References m_isFrozen.
 {
    // m_pos=m_pos;
     std::cout<<"frozen\n";
     m_isFrozen=true;
 }
ngl::Vec3 Enemy::getPosition () inline
inline functions to get the position of enemy
returns enemy pos
Definition at line 38 of file Enemy.h.
References m_pos.
 {return m_pos;}
bool Enemy::isFrozen () inline
checks if current enemy is inactive/frozen
m_isFrozen returns state of enemy
Definition at line 69 of file Enemy.h.
References m_isFrozen.
 {return m_isFrozen;}
void Enemy::move (const ngl::Vec3 & _playerPos)
methods to initially draw the enemy at creation time
_playerPos player position passed in
Definition at line 44 of file Enemy.cpp.
References distanceCalc(), fleeWalls(), m_behaviour, m_isFrozen, m_maxAccelerate, m_pos, m_prevDistance, m_prey, m_speed, setChase(), setSteer(), setTarget(), and updatePosition().
 {
     if(m_behaviour==true){
          m_isFrozen=false;
         //set prey to be player
         m_prey= _playerPos; //player
         //calc distance between player and enemy
         float distance =  distanceCalc(m_prey,m_pos);
         if(distance<m_prevDistance)
         {
             m_speed+=m_maxAccelerate;
         }
         else
         {
             m_speed-=m_maxAccelerate;
         }
         m_prevDistance = distance;
         setChase(m_prey, 0.2);
         fleeWalls();
         setTarget();
         setSteer();
         updatePosition();
     }
 }
void Enemy::printPos () private
function to check the current positions of the enemies
used for debugging
Definition at line 181 of file Enemy.cpp.
References m_pos.
 {
     std::cout<< m_pos.m_x<<"\n";
     std::cout<< m_pos.m_z<<"\n";
     //std::cout<< m_pos.m_z<<"\n";
 }
void Enemy::setAvoid (ngl::Vec3 _dir)
method to set avoidance force whenever enemies are about to overlap each other
_dir direction of player
Definition at line 153 of file Enemy.cpp.
References isAvoiding, m_avoid, m_dir, m_pos, m_separate, m_speed, m_steering, and m_velocity.
 {
     m_dir=_dir;
     if(isAvoiding==true)
     {
         if(m_velocity.length()!=0)
         {
           m_velocity.normalize();
         }
         ngl::Vec3 ahead=m_pos+m_velocity*90; //avoid weight 999999
         if(m_separate.length()!=0)
         {
           m_separate.normalize();
         }
     m_avoid-=(m_pos+m_velocity*m_speed*20)-ahead;
     m_steering=m_dir-m_velocity;
     m_velocity=m_avoid+m_steering+m_separate;//m_separate;
     }
 }
void Enemy::setChase (ngl::Vec3 _pos, float _targetSpeed) private
function to set the goal of the enemies
Parameters
[in] _pos position of player
_targetSpeed player speed
Definition at line 27 of file Enemy.cpp.
References distanceCalc(), m_goal, m_pos, and m_prey.
 {
     float predict = distanceCalc(m_prey, m_pos)/10;
     //  m_goal=(_pos+_targetSpeed*predict)-m_pos; //MVC  compiler
     //for each x/y/z component
     //gcc compiler
     m_goal.m_x=(_pos.m_x+_targetSpeed*predict)-m_pos.m_x;
     m_goal.m_y=(_pos.m_y+_targetSpeed*predict)-m_pos.m_y;
     m_goal.m_z=(_pos.m_z+_targetSpeed*predict)-m_pos.m_z;
   if(m_goal.length()!=0)
   {
     m_goal.normalize();
   }
 }
void Enemy::setHit (bool _h, int _hitCount) inline
methods to check if enemy has collided with player
Parameters
[in] _h if a collision's made
_hitCount amounts of hits
Definition at line 54 of file Enemy.h.
References m_hit, and m_hitCount.
 {m_hit=_h,_hitCount=m_hitCount;}
void Enemy::setPosition (ngl::Vec3 _pos) inline
inline functions to set the position of enemy
_pos enemy position to be set
Definition at line 43 of file Enemy.h.
References m_pos.
 {m_pos=_pos;}
void Enemy::setPrey (const ngl::Vec3 & _playerPos)
method to calculate the distance between the prey and enemy
_playerPos player position reference passed in as prey
Definition at line 21 of file Enemy.cpp.
References distanceCalc(), m_pos, m_prevDistance, and m_prey.
 {
     m_prey=_playerPos;
     m_prevDistance=distanceCalc(m_prey, m_pos);
 }
void Enemy::setSteer () private
function to set the steering behavour of the enemies
Definition at line 124 of file Enemy.cpp.
References m_steering, m_target, and m_velocity.
 {
       m_steering = m_target-m_velocity;
       if(m_steering.length()!=0)
       {
         m_steering.normalize();
       }
 }
void Enemy::setTarget () private
function to set the target of the enemies
Definition at line 113 of file Enemy.cpp.
References m_avoid, m_avoidWeight, m_flee, m_goal, and m_target.
 {
   m_goal*=30;
   m_avoid*=m_avoidWeight;
   m_target=m_goal+m_flee+m_avoid;
   if(m_target.length()!=0)
   {
     m_target.normalize();
   }
 }
void Enemy::updatePosition () private
combines all the behaviours and updates the enemy positions
Definition at line 133 of file Enemy.cpp.
References m_maxSpeed, m_minSpeed, m_pos, m_speed, m_steering, and m_velocity.
 {
   m_velocity +=(m_steering/0.5);
   if(m_speed>m_maxSpeed)
   {
     m_speed=m_maxSpeed;
   }
   else if(m_speed<m_minSpeed)
   {
     m_speed=m_minSpeed;
   }
   if(m_velocity.length()!=0)
   {
     m_velocity.normalize();
   }
   m_velocity*=m_speed*0.3;
   m_pos =( m_pos+m_velocity);
 }
Member Data Documentation
ngl::Vec3 Enemy::desiredVelocity private
Definition at line 102 of file Enemy.h.
bool Enemy::isAvoiding =true private
flag if enemy is using avoidance force
Definition at line 80 of file Enemy.h.
ngl::Vec3 Enemy::m_avoid private
Definition at line 104 of file Enemy.h.
float Enemy::m_avoidWeight private
Definition at line 123 of file Enemy.h.
bool Enemy::m_behaviour =true private
flag if enemy is using behaviour forces
Definition at line 84 of file Enemy.h.
ngl::Vec3 Enemy::m_dir private
forces to calculate behaviors for enemies
Definition at line 96 of file Enemy.h.
ngl::Vec3 Enemy::m_flee private
Definition at line 98 of file Enemy.h.
ngl::Vec3 Enemy::m_goal private
Definition at line 103 of file Enemy.h.
bool Enemy::m_hit =false private
flag hit
Definition at line 75 of file Enemy.h.
int Enemy::m_hitCount private
Definition at line 76 of file Enemy.h.
bool Enemy::m_isFrozen private
flag if enemy has gone over bounds and is not moving
Definition at line 88 of file Enemy.h.
float Enemy::m_maxAccelerate private
Definition at line 115 of file Enemy.h.
float Enemy::m_maxSpeed private
Definition at line 121 of file Enemy.h.
float Enemy::m_minSpeed private
Definition at line 122 of file Enemy.h.
ngl::Vec3 Enemy::m_pos private
enemy position
Definition at line 109 of file Enemy.h.
float Enemy::m_prevDistance private
relevant weights applied to forces
Definition at line 113 of file Enemy.h.
ngl::Vec3 Enemy::m_prey private
Definition at line 97 of file Enemy.h.
float Enemy::m_randAccel private
Definition at line 116 of file Enemy.h.
ngl::Vec3 Enemy::m_separate private
Definition at line 105 of file Enemy.h.
float Enemy::m_speed private
Definition at line 114 of file Enemy.h.
ngl::Vec3 Enemy::m_steering private
Definition at line 100 of file Enemy.h.
ngl::Vec3 Enemy::m_target private
Definition at line 99 of file Enemy.h.
ngl::Vec3 Enemy::m_velocity private
Definition at line 101 of file Enemy.h.
float Enemy::m_xmax private
Definition at line 117 of file Enemy.h.
float Enemy::m_xmin private
Definition at line 118 of file Enemy.h.
float Enemy::m_zmax private
Definition at line 119 of file Enemy.h.
float Enemy::m_zmin private
Definition at line 120 of file Enemy.h.
bool Enemy::preyIsActive private
flag check if prey is set
Definition at line 92 of file Enemy.h.
The documentation for this class was generated from the following files:
Enemy.h
Enemy.cpp