Disaster: PhongFragment.glsl File Reference
PhongFragment.glsl File Reference
Classes
struct Materials
Material structure.
struct LightInfo
light structure
Functions
layout (location=0) out vec4 fragColour
a simple phong shader
void PointLight1 (in vec3 _normal, inout vec4 _ambient, inout vec4 _diffuse, inout vec4 _specular)
A function to calculate Point light values.
void PointLight2 (in vec3 _normal, inout vec4 _ambient, inout vec4 _diffuse, inout vec4 _specular)
A function to calculate Point light values.
void PointLight3 (in vec3 _normal, inout vec4 _ambient, inout vec4 _diffuse, inout vec4 _specular)
A function to calculate Point light values.
void PointLight4 (in vec3 _normal, inout vec4 _ambient, inout vec4 _diffuse, inout vec4 _specular)
A function to calculate Point light values.
void main ()
Variables
in vec3 fragmentNormal
[in] The Fragment normal
in vec3 vertColour
[in] The vertex colour
uniform int myflag
Uniform integer flag.
uniform Materials material
Material information from structure passed from our program.
uniform LightInfo light1
Light information from structure to light 1.
uniform LightInfo light2
Light information from structure to light 2.
uniform LightInfo light3
Light information from structure to light 3.
uniform LightInfo light4
Light information from structure to light 4.
in vec3 lightDir
[in] Light direction
in vec3 halfVector
[in] the blinn half vector
in vec3 eyeDirection
[in] the eye direction
Function Documentation
layout (location = 0)
a simple phong shader
UV values from VAO.
[in] The UV data passed in
[in] The normal data passed in
Author
Tia-Louise Heeger
Version
1.0
27/05/17
[out] Output fragment colour
void main (void)
Vec4 for complete ambient value
Vec4 for complete diffuse value
Vec4 for complete specular value
complete phong calulation value for Point light 1
complete phong calulation value for Point light 2
complete phong calulation value for Point light 3
complete phong calulation value for Point light 4
fragmnet colour equals the complete phong model
If stament to swtich between phong shader and flat diffuse colour shader
Enaples Point light within the phong shader
Enables flat diffuse shader
Definition at line 200 of file PhongFragment.glsl.
References fragmentNormal, myflag, PointLight1(), PointLight2(), PointLight3(), PointLight4(), and vertColour.
 {
     vec4 ambient=vec4(0.0);
     vec4 diffuse=vec4(0.0);
     vec4 specular=vec4(0.0);
     PointLight1(fragmentNormal,ambient,diffuse,specular);
     PointLight2(fragmentNormal,ambient,diffuse,specular);
     PointLight3(fragmentNormal,ambient,diffuse,specular);
     PointLight4(fragmentNormal,ambient,diffuse,specular);
     fragColour=ambient+diffuse+specular;
     if(myflag==0)
     {
         fragColour=ambient+diffuse+specular;
     }
     else
     {
         fragColour= vec4(vertColour,1);
     }
 }
void PointLight1 (in vec3 _normal, inout vec4 _ambient, inout vec4 _diffuse, inout vec4 _specular)
A function to calculate Point light values.
Parameters
[in] _normal,the normal vector
[in,out] _ambient value of light1
[in,out] _diffuse value of light1
[in,out] _specular value of light1
normal dot VP
normal dot half vector value
pf value
calulations for complete phong model for light 1
Definition at line 84 of file PhongFragment.glsl.
References Materials::ambient, LightInfo::ambient, Materials::diffuse, LightInfo::diffuse, halfVector, light1, material, LightInfo::position, Materials::shininess, Materials::specular, and LightInfo::specular.
 {
     float nDotVP;
     float nDotHV;
     float pf;
     nDotVP= max(0.0,dot(_normal, normalize(light1.position.xyz)));
     nDotHV= max(0.0,dot(_normal,halfVector));
     pf=clamp(nDotVP,0.0,pow(nDotHV,material.shininess));
     _ambient+=light1.ambient*material.ambient;
     _diffuse+=light1.diffuse*material.diffuse*nDotVP;
     _specular+=light1.specular*material.specular*pf;
 }
void PointLight2 (in vec3 _normal, inout vec4 _ambient, inout vec4 _diffuse, inout vec4 _specular)
A function to calculate Point light values.
Parameters
[in] _normal,the normal vector
[in,out] _ambient value of light2
[in,out] _diffuse value of light2
[in,out] _specular value of light2
normal dot VP
normal dot half vector value
pf value
calulations for complete phong model for light 1
Definition at line 116 of file PhongFragment.glsl.
References Materials::ambient, LightInfo::ambient, Materials::diffuse, LightInfo::diffuse, halfVector, light2, material, LightInfo::position, Materials::shininess, Materials::specular, and LightInfo::specular.
 {
     float nDotVP;
     float nDotHV;
     float pf;
     nDotVP= max(0.0,dot(_normal, normalize(light2.position.xyz)));
     nDotHV= max(0.0,dot(_normal,halfVector));
     pf=clamp(nDotVP,0.0,pow(nDotHV,material.shininess));
     _ambient+=light2.ambient*material.ambient;
     _diffuse+=light2.diffuse*material.diffuse*nDotVP;
     _specular+=light2.specular*material.specular*pf;
 }
void PointLight3 (in vec3 _normal, inout vec4 _ambient, inout vec4 _diffuse, inout vec4 _specular)
A function to calculate Point light values.
Parameters
[in] _normal,the normal vector
[in,out] _ambient value of light3
[in,out] _diffuse value of light3
[in,out] _specular value of light3
normal dot VP
normal dot half vector value
pf value
calulations for complete phong model for light 1
Definition at line 145 of file PhongFragment.glsl.
References Materials::ambient, LightInfo::ambient, Materials::diffuse, LightInfo::diffuse, halfVector, light3, material, LightInfo::position, Materials::shininess, Materials::specular, and LightInfo::specular.
 {
     float nDotVP;
     float nDotHV;
     float pf;
     nDotVP= max(0.0,dot(_normal, normalize(light3.position.xyz)));
     nDotHV= max(0.0,dot(_normal,halfVector));
     pf=clamp(nDotVP,0.0,pow(nDotHV,material.shininess));
     _ambient+=light3.ambient*material.ambient;
     _diffuse+=light3.diffuse*material.diffuse*nDotVP;
     _specular+=light3.specular*material.specular*pf;
 }
void PointLight4 (in vec3 _normal, inout vec4 _ambient, inout vec4 _diffuse, inout vec4 _specular)
A function to calculate Point light values.
Parameters
[in] _normal,the normal vector
[in,out] _ambient value of light4
[in,out] _diffuse value of light4
[in,out] _specular value of light4
normal dot VP
normal dot half vector value
pf value
calulations for complete phong model for light 1
Definition at line 175 of file PhongFragment.glsl.
References Materials::ambient, LightInfo::ambient, Materials::diffuse, LightInfo::diffuse, halfVector, light4, material, LightInfo::position, Materials::shininess, Materials::specular, and LightInfo::specular.
 {
     float nDotVP;
     float nDotHV;
     float pf;
     nDotVP= max(0.0,dot(_normal, normalize(light4.position.xyz)));
     nDotHV= max(0.0,dot(_normal,halfVector));
     pf=clamp(nDotVP,0.0,pow(nDotHV,material.shininess));
     _ambient+=light4.ambient*material.ambient;
     _diffuse+=light4.diffuse*material.diffuse*nDotVP;
     _specular+=light4.specular*material.specular*pf;
 }
Variable Documentation
in vec3 eyeDirection
[in] the eye direction
Definition at line 76 of file PhongFragment.glsl.
in vec3 fragmentNormal
[in] The Fragment normal
Definition at line 12 of file PhongFragment.glsl.
in vec3 halfVector
[in] the blinn half vector
Definition at line 73 of file PhongFragment.glsl.
uniform LightInfo light1
Light information from structure to light 1.
Definition at line 58 of file PhongFragment.glsl.
uniform LightInfo light2
Light information from structure to light 2.
Definition at line 61 of file PhongFragment.glsl.
uniform LightInfo light3
Light information from structure to light 3.
Definition at line 64 of file PhongFragment.glsl.
uniform LightInfo light4
Light information from structure to light 4.
Definition at line 67 of file PhongFragment.glsl.
in vec3 lightDir
[in] Light direction
Definition at line 70 of file PhongFragment.glsl.
uniform Materials material
Material information from structure passed from our program.
Definition at line 55 of file PhongFragment.glsl.
uniform int myflag
Uniform integer flag.
Definition at line 18 of file PhongFragment.glsl.
in vec3 vertColour
[in] The vertex colour
Definition at line 15 of file PhongFragment.glsl.